## Kirk_Kay_2004_Table1.R -- snapshot -> analysis CSV + public TSV
##
## Kirk, E. C., & Kay, R. F. (2004). The evolution of high visual acuity in the
## Anthropoidea. In C. F. Ross & R. F. Kay (Eds.), Anthropoid Origins: New Visions
## (pp. 539-602). Kluwer Academic/Plenum. doi:10.1007/978-1-4419-8873-7_20
## Table 1: Behavioral measurements of visual acuity in various mammalian taxa
## (37 species; acuity in c/deg from conditioned behavioral protocols; ranges and
## air/water qualifiers as printed; unspecified substrate = air per table notes).
##
## FROZEN SOURCE: kirk_kay_2004.pdf (this folder; born-digital). Snapshot built by
## Kirk_Kay_2004_extract_snapshot.py, whose --verify audits every transcribed token
## against the PDF text layer (clean 2026-08-31). Third Route-A sensory source folder;
## with Veilleux_Kirk_2014 this closes most of the fixture's VA quarantine
## (comparison/: 25 KK-citing rows -> 21 confirmed correct, 4 = the alphabetical
## offset pattern, owners named).
##
## NOTE: committed outputs were generated by Kirk_Kay_2004_mirror.py (no R in the
## build sandbox). This script is canonical; running it must reproduce them
## byte-for-byte; delete the mirror once verified.

## 0. PATHS --------------------------------------------------------
.sp <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) return(normalizePath(sub("^--file=", "", a[1])))
  if (requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()) {
    p <- rstudioapi::getSourceEditorContext()$path
    if (!nzchar(p)) p <- rstudioapi::getActiveDocumentContext()$path
    if (nzchar(p)) return(normalizePath(p))
  }
  stop("Run with Rscript file.R, or open in RStudio and click Source (save first).", call. = FALSE)
})
folder    <- dirname(.sp)
item_name <- tools::file_path_sans_ext(basename(.sp))            # "Kirk_Kay_2004_Table1"
base <- local({
  d <- folder
  while (dirname(d) != d && !file.exists(file.path(d, "__ReadMe.xlsx"))) d <- dirname(d)
  if (file.exists(file.path(d, "__ReadMe.xlsx"))) d else NA_character_
})
setwd(folder)

## 1. PACKAGES ------------------------------------------------------
library(tidyverse)
library(readxl)

## 2. LOAD FROZEN SNAPSHOT + CROSSWALK ------------------------------
snap  <- read.csv(file.path(folder, paste0(item_name, "_snapshot.csv")),
                  stringsAsFactors = FALSE, colClasses = "character", encoding = "UTF-8")
stopifnot(nrow(snap) == 37)
cross <- read.csv(file.path(folder, "reference_tables", "Kirk_Kay_2004_species_crosswalk.csv"),
                  stringsAsFactors = FALSE, encoding = "UTF-8")

## 3. CLEAN: one row per printed substrate segment ------------------
## "1.6–2.5 (air); 2.5–3.8 (water)" -> two rows; single values -> min = max;
## no qualifier -> "air (unspecified; per table notes)".
seg_pat <- "^([0-9.]+)(?:–([0-9.]+))?\\s*(?:\\((air and water|air|water)\\))?$"
long <- snap %>%
  mutate(binomial = coalesce(cross$binomial[match(scientific_name, cross$printed_name)],
                             scientific_name)) %>%
  separate_rows(visual_acuity_cdeg_as_printed, sep = ";") %>%   # temporary split column
  rename(seg = visual_acuity_cdeg_as_printed) %>%
  mutate(seg = str_squish(seg),
         va_cdeg_min = as.numeric(sub(seg_pat, "\\1", seg)),
         hi          = sub(seg_pat, "\\2", seg),
         va_cdeg_max = ifelse(nzchar(hi), as.numeric(hi), va_cdeg_min),
         sub_raw     = sub(seg_pat, "\\3", seg),
         substrate   = ifelse(nzchar(sub_raw), sub_raw, "air (unspecified; per table notes)"))
stopifnot(!anyNA(long$va_cdeg_min), all(long$va_cdeg_max >= long$va_cdeg_min))

## re-attach the FULL printed value string (both segments) per species
printed <- snap %>% select(scientific_name, va_as_printed = visual_acuity_cdeg_as_printed)

final.dataframe <- long %>%
  left_join(printed, by = "scientific_name") %>%
  transmute(Species_KK2004 = scientific_name,
            common_name_KK2004 = common_name,
            binomial, activity_pattern,
            method = "behavioral",
            substrate, va_cdeg_min, va_cdeg_max, va_as_printed,
            source_as_printed = source_as_printed,
            source = item_name)

## 4. WRITE CSV + PUBLIC TSV ---------------------------------------
write.csv(final.dataframe, file.path(folder, paste0(item_name, ".csv")), row.names = FALSE)
tsv_dir <- if (!is.na(base)) file.path(base, "__Public", "comparative-data") else NA
if (!is.na(tsv_dir) && dir.exists(tsv_dir)) {
  filecodes    <- read_excel(file.path(base, "__ReadMe.xlsx"), sheet = "Sheet1")
  item_encoded <- filecodes$`Item encoded`[match(item_name, filecodes$`Item name`)]
  if (!is.na(item_encoded) && nzchar(item_encoded))
    write.table(final.dataframe, file.path(tsv_dir, paste0(item_encoded, ".tsv")),
                sep = "\t", row.names = FALSE)
  else warning("registry row not added yet (see README) -- TSV name pinned by the mirror meanwhile")
} else warning("__Public not mounted; TSV not written -- copy later")

## 5. COMPARISONS ---------------------------------------------------
## Moved 2026-09-05 to Evo-M1-Trait-Data-restricted/restricted_checks/Kirk_Kay_2004/
## comparison/ (all checks live in the restricted repo now, per REPO_BOUNDARY.md).
## Kirk_Kay_2004_VA_offset_adjudication.csv there resolves all 25 fixture VA rows
## citing "Kirk and Kay 2004": 21 confirmed correct; 4 are the alphabetical-offset
## pattern (true owners named; Phoca r119 = correct value, displaced substrate label).
