## Koay_etal_1998_Figure6.R -- frozen figure digitisation -> analysis CSV + public TSV
##
## Koay, G., Heffner, R. S., & Heffner, H. E. (1998). Hearing in a megachiropteran
## fruit bat (Rousettus aegyptiacus). J Comp Psychol 112(4):371-382.
## doi:10.1037/0735-7036.112.4.371
##
## THE ITEM IS A FIGURE. The paper prints no comparative table: Figure 6 (p. 378)
## plots high-frequency hearing limit (highest frequency audible at 60 dB SPL,
## kHz, log axis) against functional interaural distance (us, log axis) for 68
## labeled points; the key to species and the audiogram reference for every
## point is in the Figure 6 caption printed on the FACING PAGE (p. 379),
## transcribed verbatim (page-image verified) to
## reference_tables/Koay_etal_1998_Figure6_caption_key.csv.
##
## EVERY VALUE IS DIGITISED FROM THE FIGURE (value_origin = digitised_from_figure).
## The digitisation is the Bath team's (2021; hearing data.xlsx, sheet
## "Koay 1998 extract", Fig-6 block), frozen verbatim (full precision) as
## Koay_etal_1998_Figure6_snapshot.csv. Point 13 (Macaca irus) was not
## recoverable (dense cluster) and carries NA; point 61 (beluga) appears in
## Figure 7 only, per the caption. An OLDER digitisation pass survives in
## Meeting 23 July/hearing data.xlsx -- three values in the compiled sensory
## check fixture trace to that pass, not this snapshot (see README).
##
## NOTE: committed outputs were generated by Koay_etal_1998_Figure6_mirror.py
## (no R in the build sandbox); this script is canonical and must reproduce
## them byte-for-byte. Delete the mirror once verified.

## 0. PATHS --------------------------------------------------------
.sp <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) return(normalizePath(sub("^--file=", "", a[1])))
  if (requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()) {
    p <- rstudioapi::getSourceEditorContext()$path
    if (!nzchar(p)) p <- rstudioapi::getActiveDocumentContext()$path
    if (nzchar(p)) return(normalizePath(p))
  }
  stop("Run with Rscript file.R, or open in RStudio and click Source (save first).", call. = FALSE)
})
folder    <- dirname(.sp)
item_name <- tools::file_path_sans_ext(basename(.sp))   # "Koay_etal_1998_Figure6"
base <- local({
  d <- folder
  while (dirname(d) != d && !file.exists(file.path(d, "__ReadMe.xlsx"))) d <- dirname(d)
  if (file.exists(file.path(d, "__ReadMe.xlsx"))) d else NA_character_
})
setwd(folder)
snapshot_csv <- file.path(folder, paste0(item_name, "_snapshot.csv"))
key_csv      <- file.path(folder, "reference_tables", paste0(item_name, "_caption_key.csv"))
xwalk_csv    <- file.path(folder, "reference_tables", paste0(item_name, "_species_crosswalk.csv"))
final_csv    <- file.path(folder, paste0(item_name, ".csv"))
tsv_dir      <- if (!is.na(base)) file.path(base, "__Public", "comparative-data") else NA

## 1. PACKAGES ------------------------------------------------------
library(tidyverse)
library(readxl)

## 2. LOAD ----------------------------------------------------------
snap  <- read.csv(snapshot_csv, stringsAsFactors = FALSE, colClasses = "character")
key   <- read.csv(key_csv,   stringsAsFactors = FALSE, colClasses = "character")
xwalk <- read.csv(xwalk_csv, stringsAsFactors = FALSE, colClasses = "character")
stopifnot(nrow(key) == 69, nrow(snap) == 67)

## 3. JOIN + CLEAN ---------------------------------------------------
sk <- snap[match(key$figure_id, snap$figure_id), ]
xk <- xwalk[match(key$figure_id, xwalk$figure_id), ]
final.dataframe <- tibble(
  figure_id            = key$figure_id,
  Species_Koay1998     = key$binomial_as_printed,       # verbatim, incl. the printed misprints
  common_name_Koay1998 = key$common_name_as_printed,
  corrected_binomial   = coalesce(xk$corrected_binomial, key$binomial_as_printed),
  functional_interaural_distance_us = as.numeric(sk$functional_interaural_distance_us),
  high_freq_hearing_limit_60dB_kHz  = as.numeric(sk$high_freq_hearing_limit_kHz),
  medium = key$medium, marker = key$marker,
  excluded_from_correlation = ifelse(key$marker %in% c("filled_triangle_subterranean",
                                                       "open_triangle_marine", "figure7_only"),
                                     "TRUE", "FALSE"),
  audiogram_source = key$audiogram_reference_as_printed,
  value_origin = ifelse(is.na(sk$figure_id), "", "digitised_from_figure"),
  note = case_when(
    key$figure_id == "61" ~ "beluga appears in Figure 7 only (caption); no Figure 6 point",
    is.na(sk$figure_id)   ~ "point present in the figure but not recoverable from the Bath digitisation (dense cluster); audiogram ref in audiogram_source",
    TRUE ~ "")
) %>% mutate(across(where(is.character), ~replace_na(., "")))

## 4. WRITE CSV + PUBLIC TSV ---------------------------------------
write.csv(final.dataframe, final_csv, row.names = FALSE, na = "")
if (!is.na(tsv_dir) && dir.exists(tsv_dir)) {
  filecodes    <- read_excel(file.path(base, "__ReadMe.xlsx"), sheet = "Sheet1")
  item_encoded <- filecodes$`Item encoded`[match(item_name, filecodes$`Item name`)]
  write.table(final.dataframe, file.path(tsv_dir, paste0(item_encoded, ".tsv")),
              sep = "\t", row.names = FALSE, na = "")
} else warning("__Public not mounted; TSV not written -- copy later")

## 5. COMPARISON -----------------------------------------------------
## Moved 2026-09-05 to Evo-M1-Trait-Data-restricted/restricted_checks/Koay_etal_1998/
## comparison/ (all checks live in the restricted repo now, per REPO_BOUNDARY.md).
## Koay_etal_1998_Figure6_vs_SensoryData_compiled.csv there audits the check
## fixture's Koay-citing high-frequency & interaural rows against this item:
## digitised-origin check values match exactly except 4 that trace to the OLDER
## Meeting-23-July digitisation pass or to Figure 7 (beluga); published-origin
## check values differ from the digitisation by design (compilation Rule 3
## preferred Koay's cited primaries). 7 check rows cite this paper for species
## not in the figure (Delphinus misassignment; Carollia/Phyllostomus/R. rouxii
## belong to Koay et al 2002/2003) -- compilation defects, see README.
