## Veilleux_Kirk_2014_SupplementalTable1.R -- snapshot -> analysis CSV + public TSV
##
## Veilleux, C. C., & Kirk, E. C. (2014). Visual acuity in mammals: Effects of
## eye size and ecology. Brain Behav Evol 83(1):43-53. doi:10.1159/000357830
## Supplemental Table 1: Visual and Ecological Comparative Mammalian Dataset
## (91 species; eye axial diameter, visual acuity, body mass, measurement type,
## max running speed, activity pattern, diet, + per-column sources 1-122).
##
## FROZEN SOURCE: the born-digital supplementary PDF (kept in this folder). The
## snapshot was built from it by Veilleux_Kirk_2014_SupplementalTable1_extract.py
## (positional x-coordinate binning -- plain text extraction loses empty-cell
## positions), then hand-verified against rendered page images and audited in
## full against two independent extractions (comparison/): the Bath Part-1
## student sheet (179 agree, 3 student rounding differences, 0 set differences)
## and the compiled sensory check fixture (VA-offset adjudication: all 92
## VK-citing rows resolved -- 74 correct, 18 confirmed displaced).
##
## NOTE: committed outputs were generated by the _mirror.py (no R in the build
## sandbox). This script is canonical; running it must reproduce them
## byte-for-byte; delete the mirror once verified.

## 0. PATHS --------------------------------------------------------
options(scipen = 999)   # house standard: no scientific notation in committed CSV/TSV

.sp <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) return(normalizePath(sub("^--file=", "", a[1])))
  if (requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()) {
    p <- rstudioapi::getSourceEditorContext()$path
    if (!nzchar(p)) p <- rstudioapi::getActiveDocumentContext()$path
    if (nzchar(p)) return(normalizePath(p))
  }
  stop("Run with Rscript file.R, or open in RStudio and click Source (save first).", call. = FALSE)
})
folder    <- dirname(.sp)
item_name <- tools::file_path_sans_ext(basename(.sp))   # "Veilleux_Kirk_2014_SupplementalTable1"
base <- local({
  d <- folder
  while (dirname(d) != d && !file.exists(file.path(d, "__ReadMe.xlsx"))) d <- dirname(d)
  if (file.exists(file.path(d, "__ReadMe.xlsx"))) d else NA_character_
})
setwd(folder)
snapshot_csv <- file.path(folder, paste0(item_name, "_snapshot.csv"))
final_csv    <- file.path(folder, paste0(item_name, ".csv"))
tsv_dir      <- if (!is.na(base)) file.path(base, "__Public", "comparative-data") else NA

## 1. PACKAGES ------------------------------------------------------
library(tidyverse)
library(readxl)

## 2. LOAD FROZEN SNAPSHOT -----------------------------------------
snap <- read.csv(snapshot_csv, stringsAsFactors = FALSE, check.names = FALSE,
                 colClasses = "character", encoding = "UTF-8")
stopifnot(nrow(snap) == 91)

## 3. CLEAN ---------------------------------------------------------
num <- function(x) suppressWarnings(as.numeric(ifelse(x %in% c("", "NA"), NA, x)))
src_va   <- str_squish(snap$src_VA)
## flattened superscript 2 on "this study" haplorhine rows = acuity from cone density
cone     <- grepl("\\]2$", src_va)
src_va   <- sub("2$", "", src_va)
src_adbm <- str_squish(snap$src_AD_BM)
rmf      <- grepl("\\*\\*", src_adbm)     # legend **: AD estimated from retinal magnification factor
src_adbm <- gsub("\\*\\*", "", src_adbm)
bm_kg    <- num(snap$BM)

final.dataframe <- tibble(
  Order_VK2014   = snap$Order,            # printed group rows, verbatim (incl. "Primates- Haplorhines*")
  Species_VK2014 = snap$Species,          # printed name, verbatim (9 misspellings kept -- see crosswalk)
  eye_axial_diameter_mm = num(snap$AD),
  ad_estimated_from_RMF = ifelse(rmf, "TRUE", "FALSE"),
  visual_acuity_cdeg    = num(snap$VA),
  va_cone_density_footnote2 = ifelse(cone, "TRUE", "FALSE"),
  body_mass_kg_VK = bm_kg,
  `Body_mass.g`   = bm_kg * 1000,         # kg -> g (project unit, HOWTO 6)
  measurement_type = snap$MT,             # A = anatomical, B = behavioral
  max_running_speed_kph = num(snap$MRS),
  activity_pattern = snap$AP,             # D / C / N
  diet             = snap$D1,             # H / P ("active predator", legend footnote 1)
  va_this_study    = ifelse(startsWith(src_va, "this study"), "TRUE", "FALSE"),
  src_VA = src_va, src_AD_BM = src_adbm,
  src_D_AP = str_squish(snap$src_D_AP), src_MRS = str_squish(snap$src_MRS)
) %>% mutate(across(where(is.character), ~replace_na(., "")))

## 4. WRITE CSV + PUBLIC TSV ---------------------------------------
write.csv(final.dataframe, final_csv, row.names = FALSE, na = "")
if (!is.na(tsv_dir) && dir.exists(tsv_dir)) {
  filecodes    <- read_excel(file.path(base, "__ReadMe.xlsx"), sheet = "Sheet1")
  item_encoded <- filecodes$`Item encoded`[match(item_name, filecodes$`Item name`)]
  write.table(final.dataframe, file.path(tsv_dir, paste0(item_encoded, ".tsv")),
              sep = "\t", row.names = FALSE, na = "")
} else warning("__Public not mounted; TSV not written -- copy later")

## 5. COMPARISONS ---------------------------------------------------
## comparison/ holds: ..._vs_Part1_sheet.csv (student extraction audit) and
## ..._VA_offset_adjudication.csv -- the check fixture's 92 VK-citing VA rows
## resolved against this primary (74 correct, 18 displaced; the displaced values'
## true owners are named). This is the build that lifts the VA quarantine for
## VK-sourced values; Kirk & Kay 2004 covers most of the remainder.
