---
title: "MyRTutorials"
author: "Alexandra de Sousa"
date: "03/05/2019"
output: html_document
---





#set working directory
```{r}
setwd("~/Dropbox/COLLABORATIVE/Orlin/Visual_Auditory_Heffner")
##or use the pull-down menu to set working directory, under Session
```

## Merging datasets

See https://kb.iu.edu/d/azux


#load first dataset
```{r}
dataset1 <-read.table("PanTHERIA_1-0_WR93_Aug2008.csv", sep = ",", header = TRUE)
```

#view first dataset
```{r}
View(dataset1)
```

#load second dataset
```{r}
dataset2 <-read.table("VA_hearingdata.csv", sep = ",", header = TRUE)
```

#view second dataset
```{r}
View(dataset2)
```

#merge.all datasets
```{r}
merged.data.all <- merge(dataset1, dataset2, by="Species", all=TRUE)
```

#view merged dataset
```{r}
View(merged.data.all)
```

#export merged dataset
```{r}
write.csv(merged.data.all, "VA_hearingdata_Pantheria.csv")
```


#merge datasets
```{r}
merged.data <- merge(dataset1, dataset2, by="MSW05_Binomial")
```

#view merged dataset
```{r}
View(merged.data)
```

#export merged dataset
```{r}
write.csv(merged.data, "VA_PanTheria.csv")
```


