## Heffner_etal_2020_Figure3.R -- frozen figure extraction -> analysis CSV + public TSV
##
## Heffner, R. S., Koay, G., & Heffner, H. E. (2020). Hearing and sound
## localization in Cottontail rabbits, Sylvilagus floridanus.
## J Comp Physiol A 206:543-552. doi:10.1007/s00359-020-01424-8
##
## THE ITEM IS A FIGURE. Figure 3 (journal p. 548) plots high-frequency hearing
## limit at 60 dB SPL (kHz) against functional interaural distance (us), both on
## log axes, for n = 74 species in the regression plus 3 subterranean species
## excluded from it. The paper prints no comparative table.
##
## HOW THE VALUES WERE OBTAINED. The PDF is born-digital, so the figure is
## vector art: every marker is a path with exact page coordinates and every axis
## tick is a line. Heffner_etal_2020_Figure3_extract.py reads those, least-squares
## fits the two log axes against the tick values (max relative residual 0.57% x,
## 0.54% y -- the figure's own tick-placement precision), and converts marker
## centres to data units. That is reproducible and far more precise than pixel
## digitisation, but the values are still FIGURE-DERIVED: value_origin =
## digitised_from_figure on every row.
##
## IMPORTANT -- THIS FIGURE CARRIES NO PER-POINT REFERENCES. Unlike Koay et al.
## 1998 Fig. 6 (whose caption lists an audiogram source for every point), the
## Fig. 3 caption gives only the symbol scheme. The comparative points are
## therefore UNATTRIBUTED compiled values: keep them for provenance, never merge
## them. The only mergeable data in this paper are the Cottontail rabbit's own
## measurements, which are stated numerically in the text and are collected in
## reference_tables/Heffner_etal_2020_cottontail_values_from_text.csv
## (including the paper's internal 56 vs 32 kHz contradiction -- see README).
##
## SPECIES IDENTITY. Only 42 of the ~79 plotted markers carry a printed label,
## and the labels sit in a dense cluster, so label-to-marker assignment is an
## interpretive step kept in its own table
## (reference_tables/..._label_assignment.csv, built by ..._assign.py) with an
## explicit confidence column: 15 assignments are independently validated
## against Koay_etal_1998_Figure6.csv, and ambiguous ones are flagged rather
## than guessed.
##
## NOTE: committed outputs were generated by Heffner_etal_2020_Figure3_mirror.py
## (no R in the build sandbox); this script is canonical and must reproduce them
## byte-for-byte. Delete the mirror once verified.

## 0. PATHS --------------------------------------------------------
.sp <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) return(normalizePath(sub("^--file=", "", a[1])))
  if (requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()) {
    p <- rstudioapi::getSourceEditorContext()$path
    if (!nzchar(p)) p <- rstudioapi::getActiveDocumentContext()$path
    if (nzchar(p)) return(normalizePath(p))
  }
  stop("Run with Rscript file.R, or open in RStudio and click Source (save first).", call. = FALSE)
})
folder    <- dirname(.sp)
item_name <- tools::file_path_sans_ext(basename(.sp))   # "Heffner_etal_2020_Figure3"
base <- local({
  d <- folder
  while (dirname(d) != d && !file.exists(file.path(d, "__ReadMe.xlsx"))) d <- dirname(d)
  if (file.exists(file.path(d, "__ReadMe.xlsx"))) d else NA_character_
})
setwd(folder)
snapshot_csv <- file.path(folder, paste0(item_name, "_snapshot.csv"))
assign_csv   <- file.path(folder, "reference_tables", paste0(item_name, "_label_assignment.csv"))
final_csv    <- file.path(folder, paste0(item_name, ".csv"))
tsv_dir      <- if (!is.na(base)) file.path(base, "__Public", "comparative-data") else NA

## 1. PACKAGES ------------------------------------------------------
library(tidyverse)
library(readxl)

## 2. LOAD ----------------------------------------------------------
snap   <- read.csv(snapshot_csv, stringsAsFactors = FALSE, colClasses = "character")
assign <- read.csv(assign_csv,   stringsAsFactors = FALSE, colClasses = "character")
stopifnot(nrow(snap) == 79)

## 3. LABEL BOOKKEEPING ----------------------------------------------
## the figure prints common names only; two printed blocks are not species
group_headers <- c("Prairiedogs")
merged_labels <- c("PigReindeer" =
  "Pig / Reindeer (two adjacent labels; marker not resolvable between them)")
readable <- c(
  "Blindmolerat" = "Blind mole rat", "Commonvampirebat" = "Common vampire bat",
  "Cottonrat" = "Cotton rat", "Darwin'smouse" = "Darwin's mouse",
  "Dog-facedfruitbat" = "Dog-faced fruit bat", "Domesticmouse" = "Domestic mouse",
  "Domesticrabbit" = "Domestic rabbit", "Egyptianfruitbat" = "Egyptian fruit bat",
  "Foxsquirrel" = "Fox squirrel", "Guineapig" = "Guinea pig", "Hoodedrat" = "Hooded rat",
  "Jamaicanfruitbat" = "Jamaican fruit bat", "Kangaroorat" = "Kangaroo rat",
  "Killerwhale" = "Killer whale", "Nakedmolerat" = "Naked mole rat",
  "Short-tailedfruitbat" = "Short-tailed fruit bat",
  "Straw-coloredfruitbat" = "Straw-colored fruit bat", "White-taileddeer" = "White-tailed deer",
  "Woodrat" = "Wood rat", "Black-tailed" = "Black-tailed prairie dog",
  "White-tailed" = "White-tailed prairie dog")
subterranean <- c("Naked mole rat", "Gopher", "Blind mole rat")
aquatic <- c("Porpoise", "Killer whale")
bats <- c("Short-tailed fruit bat", "Jamaican fruit bat", "Common vampire bat",
          "Egyptian fruit bat", "Dog-faced fruit bat", "Straw-colored fruit bat")
rabbits <- c("Cottontail", "Domestic rabbit")

lab <- assign %>%
  mutate(is_header = label_as_printed %in% group_headers,
         name = ifelse(label_as_printed %in% names(readable),
                       readable[label_as_printed], label_as_printed)) %>%
  group_by(marker_id) %>%
  summarise(
    species_label_as_printed = paste(name[!is_header], collapse = " | "),
    label_confidence = if (sum(!is_header) > 1) "AMBIGUOUS_marker_claimed_by_2_labels"
                       else first(confidence),
    note = paste(na.omit(c(
      if (any(is_header)) "printed group heading 'Prairiedogs' resolves here; the species labels are the two prairie dogs" else NA,
      if (any(label_as_printed %in% names(merged_labels)))
        unname(merged_labels[label_as_printed[label_as_printed %in% names(merged_labels)]][1]) else NA,
      if (sum(!is_header) > 1) "two printed labels resolve to this marker" else NA)),
      collapse = "; "), .groups = "drop")

final.dataframe <- snap %>%
  left_join(lab, by = "marker_id") %>%
  transmute(
    marker_id,
    functional_interaural_distance_us = as.numeric(functional_interaural_distance_us),
    high_freq_hearing_limit_60dB_kHz  = as.numeric(high_freq_hearing_limit_60dB_kHz),
    species_label_as_printed = replace_na(species_label_as_printed, ""),
    label_confidence = ifelse(nzchar(replace_na(species_label_as_printed, "")),
                              replace_na(label_confidence, ""), "unlabelled_in_figure"),
    caption_group = case_when(
      species_label_as_printed %in% subterranean ~ "subterranean rodent (diamond)",
      species_label_as_printed %in% aquatic      ~ "aquatic/amphibious (triangle)",
      species_label_as_printed %in% bats         ~ "bat (square)",
      species_label_as_printed %in% rabbits      ~ "rabbit (star)",
      nzchar(species_label_as_printed) & grey_fill == "TRUE" ~ "rodent (grey fill)",
      TRUE ~ ""),
    excluded_from_regression = ifelse(species_label_as_printed %in% subterranean, "TRUE", ""),
    marker_filled = filled, marker_grey_fill = grey_fill,
    value_origin = "digitised_from_figure",
    note = replace_na(note, ""))

## 4. WRITE CSV + PUBLIC TSV ---------------------------------------
write.csv(final.dataframe, final_csv, row.names = FALSE, na = "")
if (!is.na(tsv_dir) && dir.exists(tsv_dir)) {
  filecodes    <- read_excel(file.path(base, "__ReadMe.xlsx"), sheet = "Sheet1")
  item_encoded <- filecodes$`Item encoded`[match(item_name, filecodes$`Item name`)]
  write.table(final.dataframe, file.path(tsv_dir, paste0(item_encoded, ".tsv")),
              sep = "\t", row.names = FALSE, na = "")
} else warning("__Public not mounted; TSV not written -- copy later")

## 5. COMPARISON -----------------------------------------------------
## comparison/..._vs_SensoryData_compiled.csv: the compiled sensory check
## fixture cites this paper once (Cottontail high-frequency limit, 56 kHz) and
## that value agrees exactly with the paper's text.
