## SensoryData_compiled.R -- Sensory Data.xlsx (Bath audiovisual compilation) -> long check-fixture CSV
##
## CANONICAL cleaning script for the compiled sensory CHECK FIXTURE (owner
## decision 2026-08-31: the Bath compilation is not a paper, so it is NOT a
## registry item -- no registry row, no public TSV). Source: the frozen archive
## workbook ../_incoming_Bath_archive_20260814/Sensory Data.xlsx (digital-native,
## sha256 b3a6430777192406...aa13b309; archive is read-only by owner instruction).
## Role: each Route-A primary-source folder (Heffner/Koay/Veilleux-Kirk papers)
## is audited against this table in its comparison/ step, matching on the
## reference column short codes.
##
## NOTE: the committed outputs were generated by SensoryData_compiled_mirror.py
## (offline Python mirror; no R available in the build sandbox). This script is
## the canonical definition; running it must reproduce the mirror's outputs
## byte-for-byte. Any diff is a bug in one of the two.
##
## QC decisions baked in (owner decisions, 2026-08-31):
##  * Check fixture only; NOT registered, NOT public, NOT added to any __merging_* compile.
##  * VA quarantine: every visual_acuity_max value carries
##    qc_status = "quarantined_va_offset" (24-row offset error; see
##    ____Sensory_audiovisual/sensory_VA_offset_audit.csv and the ReadMe).
##    Do not use VA values until re-derived from Veilleux & Kirk 2014 / Kirk & Kay 2004.
##  * Long format: one row per species-row x trait value, deterministic value_id.
##  * Class gate: 4 bird species carry class = "Aves"; register, don't compile.
##  * Values with >=4 decimals were digitised off figures by the original curators
##    (chiefly Koay et al 1998 Fig. 6, Heffner 2018) -> value_origin flag.

## 0. PATHS --------------------------------------------------------
.sp <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(a)) return(normalizePath(sub("^--file=", "", a[1])))
  if (requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()) {
    p <- rstudioapi::getSourceEditorContext()$path
    if (!nzchar(p)) p <- rstudioapi::getActiveDocumentContext()$path
    if (nzchar(p)) return(normalizePath(p))
  }
  stop("Run with Rscript file.R, or open in RStudio and click Source (save first).", call. = FALSE)
})
folder    <- dirname(.sp)
item_name <- tools::file_path_sans_ext(basename(.sp))     # "SensoryData_compiled"
base <- local({
  d <- folder
  while (dirname(d) != d && !file.exists(file.path(d, "__ReadMe.xlsx"))) d <- dirname(d)
  if (file.exists(file.path(d, "__ReadMe.xlsx"))) d else NA_character_
})
setwd(folder)
src_xlsx  <- file.path(dirname(folder), "_incoming_Bath_archive_20260814", "Sensory Data.xlsx")
audit_csv <- file.path(dirname(folder), "sensory_VA_offset_audit.csv")
final_csv <- file.path(folder, paste0(item_name, ".csv"))

## 1. PACKAGES ------------------------------------------------------
library(tidyverse)
library(readxl)

## 2. LOAD FROZEN SOURCE -------------------------------------------
raw <- read_excel(src_xlsx, sheet = "Data", col_names = FALSE, n_max = 168)
va_audit <- read.csv(audit_csv, stringsAsFactors = FALSE, check.names = FALSE)

## 3. TRAIT MAP -----------------------------------------------------
## column positions in the Data sheet (1-based); comment_col NA where absent
traits <- tribble(
  ~trait,                              ~value_col, ~unit,          ~ref_col, ~comment_col,
  "visual_acuity_max",                  3,  "c/deg",        7,  6,
  "audible_freq_low_60dBSPL",           8,  "kHz",          9,  10,
  "audible_freq_high_60dBSPL",          11, "kHz",          12, 13,
  "hearing_range",                      14, "octaves",      15, NA,
  "interaural_distance_functional",     16, "us",           17, 18,
  "best_sensitivity",                   19, "dB",           20, 21,
  "best_frequency",                     22, "kHz",          23, 24,
  "sound_localization_threshold",       25, "deg",          26, 27,
  "field_of_best_vision_width",         28, "deg",          29, 30,
  "binocular_field",                    31, "deg",          32, NA,
  "binaural_phase_cue_max_freq",        33, "kHz",          34, NA,
  "binaural_phase_cue",                 35, "Y/N",          36, 37,
  "binaural_intensity_difference_cue",  38, "Y/N",          39, 40,
  "monaural_pinna_cues",                41, "Y/N",          42, NA,
  "trophic_level",                      43, "ordinal 1-5",  44, NA
)
birds <- c("Anas platyrhynchos", "Columba livia domestica",
           "Melopsittacus undulatus", "Taeniopygia guttata")

squish1 <- function(x) str_squish(replace_na(as.character(x), ""))
num15   <- function(x) ifelse(is.na(x), NA_character_, sprintf("%.15g", x))
dec_ge4 <- function(x) {                       # digitised-off-figure heuristic
  s <- sprintf("%.15g", x)
  grepl("\\.", s) & nchar(sub("^[^.]*\\.", "", s)) >= 4
}

## 4. RESHAPE TO LONG ----------------------------------------------
rows <- list()
for (r in 2:168) {
  sp <- squish1(raw[[1]][r]); if (!nzchar(sp)) next
  common    <- squish1(raw[[2]][r])
  substrate <- squish1(raw[[4]][r])
  va_method <- squish1(raw[[5]][r])
  for (i in seq_len(nrow(traits))) {
    v <- raw[[traits$value_col[i]]][r]
    if (is.na(v) || !nzchar(str_squish(as.character(v)))) next
    trait  <- traits$trait[i]
    vnum   <- suppressWarnings(as.numeric(v))
    origin <- if (!is.na(vnum) && dec_ge4(vnum)) "digitised_from_figure" else "published"
    qc <- "ok"; note <- ""
    if (trait == "visual_acuity_max") {
      qc <- "quarantined_va_offset"
      a  <- va_audit[va_audit$SensoryData_excel_row == r, ]
      if (nrow(a) == 1) {
        note <- paste0("VA column quarantined pending re-derivation from Veilleux & Kirk 2014 / Kirk & Kay 2004; offset audit status: ", a$status)
        if (nzchar(a$SensoryData_value_is_Part1_value_of))
          note <- paste0(note, "; value belongs upstream to: ", a$SensoryData_value_is_Part1_value_of)
      } else {
        note <- "VA column quarantined pending re-derivation; row absent from sensory_VA_offset_audit.csv"
      }
    } else if (trait == "audible_freq_high_60dBSPL" && sp == "Delphinapterus leucas") {
      qc <- "curator_flag"; note <- "Notesissues #2: extrapolated Koay et al 1998 value conflicts with primary references"
    } else if (trait == "sound_localization_threshold" && sp == "Rattus norvegicus") {
      qc <- "curator_flag"; note <- "Notesissues #1: Heffner & Heffner 1992a value may be domestic vs albino Norway rat mix-up"
    }
    rows[[length(rows) + 1]] <- tibble(
      value_id  = sprintf("SensoryData_r%03d_%s", r, trait),
      Species_SensoryData = sp, common_name = common,
      class     = if (sp %in% birds) "Aves" else "Mammalia",
      source_excel_row = r, trait = trait,
      value     = if (!is.na(vnum)) sprintf("%.15g", vnum) else squish1(v),
      value_num = vnum, unit = traits$unit[i],
      method    = if (trait == "visual_acuity_max") va_method else "",
      substrate = substrate,
      reference = squish1(raw[[traits$ref_col[i]]][r]),
      comment   = if (!is.na(traits$comment_col[i])) squish1(raw[[traits$comment_col[i]]][r]) else "",
      value_origin = origin, qc_status = qc, qc_note = note)
  }
}
final.dataframe <- bind_rows(rows)   # source row order preserved; no locale-dependent sort
stopifnot(nrow(final.dataframe) == 763)

## 5. WRITE CHECK-FIXTURE CSV ---------------------------------------
write.csv(final.dataframe, final_csv, row.names = FALSE, na = "")
