# SELECT merge — compile brain-structure VOLUMES from a HAND-CHOSEN subset of tables.
# Sibling of volumes_compiled.R (canonical core collection) and volumes_compiled_DeCasien.R (DeCasien subset).
# Same engine; what differs is (a) the selection block below, (b) the output suffix, and (c) an
# explicit, hand-editable VALUE-FLAG registry that can veto a value even when it is the most recent.
#
# WHY THIS SCRIPT EXISTS
#   volumes_compiled.R merges everything and splits sources into Tier 1 (Stephan collection, most
#   recent wins) and Tier 2 (independent series, cross-team averaged). Sometimes you want the
#   opposite: a small, deliberately chosen set of tables treated as ONE evolving dataset, where the
#   most recent measurement of each (species x structure) supersedes the older ones — except where
#   you have decided a particular value must not be used, however recent it is.
#
# THE RULE IMPLEMENTED HERE
#   1. Every table in `select_datasets` is collapsed to ONE value per species x structure
#      (per-specimen tables are averaged within the table first).
#   2. Candidates are then resolved WITHIN each team by MOST RECENT `year`; ties broken by
#      `tie_rule`.
#   3. A candidate whose (Source, Species, Variable) matches a `skip` row in
#      volumes_select_value_flags.csv is REMOVED BEFORE the recency pick, so the next-most-recent
#      unflagged value wins instead. Every such skip is written to the generated README and to
#      volumes_select_flagged_not_used.csv.
#   4. If the selection names more than one team, the surviving per-team values are AVERAGED across
#      teams exactly as in volumes_compiled.R. With a single team (the default) this is a no-op.
#   5. Body/brain mass follow `mass_rule` (default: pinned to the Stephan 1981 reference tables,
#      as in volumes_compiled.R; set to "recent" to treat mass like any other variable).
#   6. Step 7 hemisphere reconciliation is unchanged: one-side volumes get a both-sides partner
#      (left + right where both exist, otherwise 2x with a flag).
#
# TO CHANGE THE SELECTION: edit `select_datasets` only. Everything downstream adapts. A table needs
# (i) a row in __ReadMe.xlsx (or an `enc_override` entry) so its TSV can be found, and (ii) a term
# map — either rows in standardized_term_volumes.csv or a per-reference file in
# standardized_term_by_reference/ (this script falls back to the per-reference file automatically).
#
# See README__volumes_compiled_select.md (regenerated by this script on every run).

library(tidyverse); library(readxl)

## ---- paths: self-contained (Rscript or RStudio; needs the full repo) ----
.sp <- local({
  a <- grep("^--file=", commandArgs(FALSE), value = TRUE)             # Rscript file.R
  if (length(a)) return(normalizePath(sub("^--file=", "", a[1])))
  if (requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()) {
    p <- rstudioapi::getSourceEditorContext()$path                    # RStudio: Source
    if (!nzchar(p)) p <- rstudioapi::getActiveDocumentContext()$path  # RStudio: Run
    if (nzchar(p)) return(normalizePath(p))
  }
  stop("Run with Rscript file.R, or open in RStudio and click Source (save first).", call. = FALSE)
})
folder <- dirname(.sp)                                                # __merging_volumes
base   <- local({                                                     # repo root (marker: __ReadMe.xlsx)
  d <- folder
  while (dirname(d) != d && !file.exists(file.path(d, "__ReadMe.xlsx"))) d <- dirname(d)
  if (file.exists(file.path(d, "__ReadMe.xlsx"))) d else NA_character_
})
if (is.na(base))
  stop("Repo root (__ReadMe.xlsx) not found above ", folder, " — this merge script needs the full ",
       "repository (it reads __Public/comparative-data and _keys).", call. = FALSE)
setwd(folder)

## ============================================================================================
## 0  OPTIONS — the whole configurable surface of this script
## ============================================================================================
selection_name <- "Stephan-collection core + de Sousa/Matano/Zilles/Bauernfeind/MacLeod/Smaers"
output_suffix  <- "_select"          # every file this script writes carries this suffix
sel_csv        <- function(stem) paste0(stem, output_suffix, ".csv")

flags_file <- "volumes_select_value_flags.csv"  # hand-edited value-flag registry (see README)
readme_out <- "README__volumes_compiled_select.md"   # GENERATED on every run
readme_intro <- "README__volumes_compiled_select.INTRO.md"  # optional hand-written prose, spliced in

# Same-year ties within a team: "first" = the earlier row in `select_datasets` wins (explicit and
# reproducible); "mean" = average the tied values; "last" = the later row wins.
tie_rule <- "first"

# Body/brain mass: "reference" = pin to the tables matching `mass_reference_pattern` (fills gaps
# from elsewhere); "recent" = treat mass like every other variable.
mass_rule <- "reference"
mass_reference_pattern <- "^Stephan_etal_1981_Table(I{1,3})$"   # Stephan 1981 Tables I / II / III

# TRUE = run step 7 (build both-hemisphere partners for one-side volumes).
do_hemisphere_reconciliation <- TRUE
# Which _left/_right stems get a both-sides partner. "auto" = every stem the selection actually has
# a _left/_right variable for (so a change of selection needs no edit here); or give an explicit
# character vector, e.g. the hard-coded insula list in volumes_compiled.R.
bilateral_stems <- "auto"
# ...minus these. de Sousa 2010 Table 1 reports V1 and LGN from the LEFT hemisphere only, and the
# doubling for those two structures has ALREADY been done by the authors: de Sousa 2010 Supp. Table 2
# and de Sousa 2013 Table 1 both publish 2x-left figures (`doubling = by_source` in
# laterality_known.csv; verified — Supp. Table 2 V1 = 2 x mean Table 1 left V1, e.g. Homo 15.2 =
# 2x7.63). Doubling Table 1's left values here as well would put a second, redundant 2x estimate of
# the same measurement into the merge, so we exclude these stems here. The two stems differ in how
# live that risk is: `Corpus_geniculatum_laterale` IS at risk (deSousa_etal_2013_Table1 is selected
# and publishes the 2x-left LGN), whereas for `Area_striata_grey_matter` the doubled figures live in
# deSousa_etal_2010_SupTable2, which is NOT selected — so excluding it prevents no redundancy today
# and simply leaves the de Sousa hominoids with a `_left` V1 and no bilateral partner. It is kept
# excluded to match volumes_compiled.R, whose step 7 iterates a hard-coded `insula_stems` list that
# never contained V1 (same outcome, different mechanism — there is no shared guard).
# Earlier wording called Supp. Table 2 "the real bilateral means" — it is not; it is the authors'
# bilateral ESTIMATE. Delete a name here to let it be doubled (the result is always flagged
# `estimated_bilateral_from_unilateral`, never silent).
#
# 2026-08-19: `Area_striata_grey_matter` REMOVED from this exclusion list. Rationale, measured
# against the then-current ledger rather than argued: of the 8 species carrying a de Sousa 2010
# Table 1 left V1, three (Macaca fascicularis, Pan paniscus, Symphalangus syndactylus) have NO
# both-sides Area_striata_grey_matter_Vol.mm3 from any source, so excluding the stem was costing
# three species a bilateral V1 for no benefit. They now gain one, flagged
# `estimated_bilateral_from_unilateral` as usual (2800, 11600, 5400 mm3).
#
# What this does NOT do, so nobody re-litigates it: the other five (Homo, Pan troglodytes, Gorilla,
# Pongo, Hylobates lar) are unaffected, because step 7's anti_join drops a derived value wherever a
# both-sides value already exists -- Frahm 1984 (Zilles 1988 for Pongo) holds those slots. That is
# the deliberate "a real both-sides value always beats a doubled estimate" rule. Whether de Sousa
# 2010's hominoid re-measurement should supersede Frahm 1984's older bilateral is a SOURCE-PREFERENCE
# question, not a laterality one, and is not decided here.
#
# `Corpus_geniculatum_laterale` STAYS excluded: deSousa_etal_2013_Table1 is selected and already
# publishes the 2x-left LGN (doubling = by_source), so doubling Table 1's left LGN as well would put
# a second, redundant 2x estimate of the same measurement into the merge.
bilateral_stems_exclude <- c("Corpus_geniculatum_laterale")

## ---- taxon filter ---------------------------------------------------------------------------
## Restrict the merge to chosen taxa. The registry is _keys/species_taxonomy.csv (Species, Order,
## Family), which already carries the project's genus-level labels (Gorilla sp., Pongo sp.,
## Tarsius sp., Cebus sp. ...), so those are matched like any binomial.
##   taxa_keep  : values to keep, or "all" for no filter.  e.g. c("Primates")
##                                                              c("Primates", "Scandentia")
##                                                              c("Hominidae", "Cercopithecidae")
##   taxa_rank  : which registry column taxa_keep refers to — "Order" or "Family".
##   taxa_unmatched : what to do with a species the registry does not cover.
##                "keep" — keep it and list it in the README (default: a missing registry row is a
##                         gap in the registry, not evidence the species is out of scope);
##                "drop" — treat unmatched as out of scope;
##                "stop" — refuse to run until every species is registered.
## Excluded species are written to volumes_taxon_excluded_select.csv with the reason, and the
## filter is applied BEFORE pooling, so long / wide / flags / audit are all consistent.
taxa_keep      <- c("Primates")
taxa_rank      <- "Order"
taxa_unmatched <- "keep"

## ============================================================================================
## 1  THE SELECTION — edit this tribble to re-point the script
## ============================================================================================
## item : must match __ReadMe.xlsx "Item name" (case-insensitive) or an `enc_override` key below.
## team : sources sharing a team are resolved by recency; different teams are averaged.
##        Leave every row on one team to get pure "most recent wins" behaviour.
## year : the date used for recency. Use the PUBLICATION year of the measurement, not of a reprint.
##
## Version 1 selection (requested 2026-08-06):
##   Stephan et al. 1981 (16 printed tables) | de Sousa et al. 2010 | de Sousa et al. 2013
##   Matano et al. 1985a/b | Smaers et al. 2017 | Zilles & Rehkämper 1988
##   Bauernfeind et al. 2013 | MacLeod et al. 2003
## All on ONE team ("Selected_collection") per the brief: same team, most recent version wins.
select_datasets <- tribble(
  ~item,                                  ~team,                  ~year,
  # -- Stephan, Frahm & Baron 1981, Folia Primatol (one paper, 16 printed tables) --------------
  "Stephan_etal_1981_TableI",             "Selected_collection",  1981,
  "Stephan_etal_1981_TableII",            "Selected_collection",  1981,
  "Stephan_etal_1981_TableIII",           "Selected_collection",  1981,
  "Stephan_etal_1981_TableIV",            "Selected_collection",  1981,
  "Stephan_etal_1981_TableV",             "Selected_collection",  1981,
  "Stephan_etal_1981_TableVI",            "Selected_collection",  1981,
  "Stephan_etal_1981_TableVII",           "Selected_collection",  1981,
  "Stephan_etal_1981_TableVIII",          "Selected_collection",  1981,
  "Stephan_etal_1981_TableIX",            "Selected_collection",  1981,
  "Stephan_etal_1981_TableX",             "Selected_collection",  1981,
  "Stephan_etal_1981_TableXI",            "Selected_collection",  1981,
  "Stephan_etal_1981_TableXII",           "Selected_collection",  1981,
  "Stephan_etal_1981_TableXIII",          "Selected_collection",  1981,
  "Stephan_etal_1981_TableXIV",           "Selected_collection",  1981,
  "Stephan_etal_1981_TableXV",            "Selected_collection",  1981,
  "Stephan_etal_1981_TableXVI",           "Selected_collection",  1981,
  # -- Frahm et al. 1982 Table 2 (neocortex: total, grey, white, lamina 1, laminae 2-6) --------
  # NB the printed white_pct_neocortex column is a PERCENTAGE, so it is deliberately not in the
  # term map: this merge carries *_Vol.mm3 only (README__merging.md, "One data type only").
  # Recover it downstream as Neocortex_white_matter / Neocortex x 100.
  "Frahm_etal_1982_Table2",               "Selected_collection",  1982,
  # -- Frahm et al. 1984 (area striata: total, grey, lamina 1, laminae 2-6, white) -------------
  "Frahm_etal_1984_Table1",               "Selected_collection",  1984,
  # -- Stephan et al. 1984 Table 1 (LGN / corpus geniculatum laterale) -------------------------
  "Stephan_etal_1984_Table1",             "Selected_collection",  1984,
  # -- Matano et al. 1985 a (cerebellar nuclei) and b (ventral pons) ---------------------------
  "Matano_etal_1985_a_Table1",            "Selected_collection",  1985,
  "Matano_etal_1985_b_Table1",            "Selected_collection",  1985,
  "Matano__1986_TableI",                  "Selected_collection",  1986,  # vestibular nuclei, ONE SIDE (_unilateral terms); superseded by Baron_etal_1988_Table1 (bilateral, all 46 spp.) where both are selected
  # -- Zilles & Rehkämper 1988 (Pongo, structure-rows) -----------------------------------------
  "Zilles_Rehkämper_1988_Table12-2",      "Selected_collection",  1988,
  # -- Stephan et al. 1988 Table 1 (body + brain weight, 52 spp) -------------------------------
  # NEWER than Stephan 1981 but `mass_rule = "reference"` pins mass to Stephan 1981 Tables I-III,
  # so this FILLS GAPS only (~7 species). To let 1988 supersede 1981, set mass_reference_pattern
  # to "^Stephan_etal_1988_TABLE1$", or mass_rule to "recent".
  # Its activity / diet_category / locomotion columns are ecology, not volumes -> not mapped;
  # they belong in __merging_body_ecology.
  "Stephan_etal_1988_TABLE1",             "Selected_collection",  1988,
  # -- MacLeod et al. 2003 (cerebellum; Table1 Yerkes sample, Table2 Hirnforschung sample) ------
  "MacLeod_etal_2003_Table1",             "Selected_collection",  2003,
  "MacLeod_etal_2003_Table2",             "Selected_collection",  2003,
  # -- de Sousa et al. 2010 (Table 1: per-specimen brain/neocortex/LEFT V1/LEFT LGN) ------------
  "deSousa_etal_2010_Table1",             "Selected_collection",  2010,
  # -- Bauernfeind et al. 2013 (insula; Table1 = LEFT, Table2 = RIGHT) --------------------------
  "Bauernfeind_etal_2013_Table1",         "Selected_collection",  2013,
  "Bauernfeind_etal_2013_Table2",         "Selected_collection",  2013,
  # -- de Sousa et al. 2013 (bilateral LGN + brain mass) ---------------------------------------
  "deSousa_etal_2013_Table1",             "Selected_collection",  2013,
  # -- Smaers et al. 2011 Suppl. Table 1 (TOTAL frontal lobe grey matter) ----------------------
  # The whole-lobe measurement, NOT a subregion: `frontal_grey_total_cm3` = left + right frontal
  # grey, per individual, 26 individuals -> 19 species (18 anthropoids + Homo, n = 8). Smaers'
  # OWN primary volumetry on the C. & O. Vogt / Stephan-Collection brains, so it is a Tier-1
  # source, not a compilation. This is the ONLY total-frontal-grey source anywhere in the merge:
  # `FrontalCortex_grey_matter_Vol.mm3` is claimed by no other item in standardized_term_volumes.csv,
  # so nothing is superseded and no species row is added — all 19 species already exist here.
  #
  # SCOPE (requested 2026-08-12): grey matter only, whole lobe only.
  #   * frontal WHITE is deliberately dropped in the reshape below (the term-map row still exists,
  #     so volumes_compiled.R is unaffected); restore one line there to bring it back.
  #   * the frontal SUBREGIONS are deliberately not taken: Suppl. Table 2 (`sec5_*`, the cumulative
  #     anterior-frontal block Smaers 2017 republishes as `prefrontal`) is NOT in this selection and
  #     is not term-mapped, and Smaers 2017 `frontal_motor` is a posterior section block.
  #     Those two do NOT partition the lobe — summed they are only ~36% of frontal_grey_total
  #     (53-68% short in all 19 spp.), so total frontal grey cannot be rebuilt from them.
  # Superseded by nothing; supersedes nothing. Smaers et al. 2010 Table 1 carries an earlier
  # vintage of the same column for 18 of these 19 species (no Homo) and is therefore not needed
  # for coverage — see crosspub_Smaers2017_FINDINGS.md for the 2010 vs 2011 value drift.
  "Smaers_etal_2011_SupplementaryTable1", "Selected_collection",  2011,
  # -- Smaers et al. 2017 Table S1 part 1 (cortical volumes) -----------------------------------
  # NEWEST table in the selection, so on recency alone it would supersede everything it covers.
  # It is a COMPILATION: primary_visual = de Sousa 2010 = Frahm 1984 area striata (value-matched
  # EXACT), prefrontal = Smaers 2011 Suppl. Table 2, other_association = a derived residual. Those
  # six columns carry `skip` rows in volumes_select_value_flags.csv and are reported in the README
  # as "flagged, not used, though more recent". Only frontal_motor (2017-unique) survives, flagged
  # `review` because it was never published anywhere it can be checked against.
  "Smaers_etal_2017_TableS1part1",        "Selected_collection",  2017
)
stopifnot(!anyDuplicated(select_datasets$item))
# `pick` = position in the tribble; used as the deterministic same-year tie-break.
select_datasets <- select_datasets %>% mutate(pick = row_number())

## ---- ABLATION SWITCH (temporary, 2026-08-17) -----------------------------------------------
## Purpose: establish a clean baseline against data_raw/Stephan_primates.csv in
## analyses_metabol_rate_structure, so that any REMAINING Stephan-vs-merge disagreement is a
## genuine defect rather than expected source precedence. Once that baseline is established,
## re-admit items one at a time and attribute each changed cell to the item that changed it.
##
## Comment out a line to RE-ADMIT that item. Delete this whole block to restore the full merge.
##
## Why these two teams and not the other post-Stephan sources: MacLeod and Smaers are the items
## that exist in this merge but NOT in Stephan_primates.csv. de Sousa 2010/2013 and Bauernfeind
## 2013 are already folded INTO that file (its LGN_Sousa, ASG_Sousa, Total_insula_volume_L and
## Granular/Dysgranular/Agranular_volume_L columns), so excluding those would CREATE asymmetry
## rather than remove it.
##
## Filtering here rather than commenting rows out of the tribble above is deliberate:
##   1. `pick` is already assigned, so the same-year tie-break order of the surviving items is
##      identical to the full-merge run. Deleting tribble rows renumbers `pick`.
##   2. The last tribble row carries no trailing comma, so commenting it out leaves a dangling
##      comma on the line above and the tribble fails to parse.
EXCLUDE_ITEMS <- c(
  "MacLeod_etal_2003_Table1",              # cerebellum, Yerkes sample -- overrides Stephan cerebellum
  "MacLeod_etal_2003_Table2",              # cerebellum, Hirnforschung sample; sole source of 'Cebus sp.'
  "Smaers_etal_2011_SupplementaryTable1",  # total frontal grey -- 'reference' role only, no compared cell
  "Smaers_etal_2017_TableS1part1"          # frontal_motor -- 'reference' role only, no compared cell
)
if (length(EXCLUDE_ITEMS)) {
  unknown <- setdiff(EXCLUDE_ITEMS, select_datasets$item)
  if (length(unknown))
    stop("EXCLUDE_ITEMS names item(s) not in select_datasets: ", paste(unknown, collapse = ", "))
  message("ABLATION: excluding ", length(EXCLUDE_ITEMS), " item(s) -- ",
          paste(EXCLUDE_ITEMS, collapse = ", "))
  select_datasets <- select_datasets %>% filter(!item %in% EXCLUDE_ITEMS)
}
## ---- end ablation switch --------------------------------------------------------------------

## ============================================================================================
## 2  Resolve each item to its TSV
## ============================================================================================
filecodes <- read_excel(file.path(base, "__ReadMe.xlsx"), sheet = "Sheet1")
# Fallback encodings, for items whose __ReadMe.xlsx row is missing or has drifted in case/spelling.
# Remove an entry once its registry row is correct. (Same list as volumes_compiled.R, trimmed to
# the items this script can select, plus Smaers 2017.)
enc_override <- c(
  # Stephan 1981: all 16 tables share the paper's single DOI 10.1159/000155963; pin it so the
  # drifted VIII/IX/X registry encodings (000155964/5/6) cannot send those tables to a missing TSV.
  "Stephan_etal_1981_TableI"     = "10.1159%2F000155963_TableI",
  "Stephan_etal_1981_TableII"    = "10.1159%2F000155963_TableII",
  "Stephan_etal_1981_TableIII"   = "10.1159%2F000155963_TableIII",
  "Stephan_etal_1981_TableIV"    = "10.1159%2F000155963_TableIV",
  "Stephan_etal_1981_TableV"     = "10.1159%2F000155963_TableV",
  "Stephan_etal_1981_TableVI"    = "10.1159%2F000155963_TableVI",
  "Stephan_etal_1981_TableVII"   = "10.1159%2F000155963_TableVII",
  "Stephan_etal_1981_TableVIII"  = "10.1159%2F000155963_TableVIII",
  "Stephan_etal_1981_TableIX"    = "10.1159%2F000155963_TableIX",
  "Stephan_etal_1981_TableX"     = "10.1159%2F000155963_TableX",
  "Stephan_etal_1981_TableXI"    = "10.1159%2F000155963_TableXI",
  "Stephan_etal_1981_TableXII"   = "10.1159%2F000155963_TableXII",
  "Stephan_etal_1981_TableXIII"  = "10.1159%2F000155963_TableXIII",
  "Stephan_etal_1981_TableXIV"   = "10.1159%2F000155963_TableXIV",
  "Stephan_etal_1981_TableXV"    = "10.1159%2F000155963_TableXV",
  "Stephan_etal_1981_TableXVI"   = "10.1159%2F000155963_TableXVI",
  "Bauernfeind_etal_2013_Table2" = "10.1016%2Fj.jhevol.2012.12.003_Table2",
  "MacLeod_etal_2003_Table1"     = "10.1016%2Fs0047-2484(03)00028-9_Table1",
  "MacLeod_etal_2003_Table2"     = "10.1016%2Fs0047-2484(03)00028-9_Table2",
  "Smaers_etal_2011_SupplementaryTable1" = "10.1159%2F000323671_SupplementaryTable1",
  "Smaers_etal_2017_TableS1part1"        = "10.1016%2Fj.cub.2017.01.020_TableS1part1",
  "Smaers_etal_2017_TableS1part2"        = "10.1016%2Fj.cub.2017.01.020_TableS1part2",
  # Matano 1986: __ReadMe.xlsx row 185 lost its "Item number" (col D), so the K/L formulas render
  # "Matano__1986_" / "10.1159%2F000156277_" with a bare trailing underscore and read_item() cannot
  # resolve the TSV. D185 has been restored to "Table I", so this override is now inert belt-and-
  # braces — the OneDrive/Excel rewriter has emptied col D on this workbook before (9 rows were
  # empty on 2026-08-12). Safe to delete once the registry has held for a while.
  "Matano__1986_TableI"                  = "10.1159%2F000156277_TableI",
  # Zilles & Rehkämper 1988 Table 12-2: the SAME class of registry drift as Matano 1986 above.
  # __ReadMe.xlsx no longer renders an "Item name" matching "Zilles_Rehkämper_1988_Table12-2", so
  # the case-insensitive lookup in read_item() finds no row and the item resolves to no encoding —
  # even though the workbook still carries the encoding for it and the TSV is present on disk as
  # __Public/comparative-data/ISBN%3A9780195043716_Table12-2.tsv. Book chapter (Orang-Utan Biology,
  # OUP), so the code is an ISBN, not a DOI.
  # NB the value below deliberately omits ".tsv" — read_item() appends the extension itself. The
  # workbook's own cell holds it WITH the extension, which would have produced "...Table12-2.tsv.tsv".
  "Zilles_Rehkämper_1988_Table12-2"      = "ISBN%3A9780195043716_Table12-2")

read_item <- function(it) {
  # Match item names CASE-INSENSITIVELY (registry drifts e.g. Table2 vs TABLE2) and strip stray
  # spaces from the encoding (cloud-edit typos like "ISBN%3A 0390..."), but keep the encoding's
  # case (DOIs/filenames are case-sensitive).
  norm <- function(x) tolower(gsub(" ", "", x))
  i   <- match(norm(it), norm(filecodes$"Item name"))
  enc <- if (!is.na(i)) gsub(" ", "", filecodes$"Item encoded"[i]) else NA_character_
  if ((is.na(enc) || !nzchar(enc)) && it %in% names(enc_override)) enc <- enc_override[[it]]
  # if the registry-resolved file is missing but we have a manual override, prefer the override
  if (!is.na(enc) && nzchar(enc) && it %in% names(enc_override) &&
      !file.exists(file.path(base, "__Public/comparative-data", paste0(enc, ".tsv"))))
    enc <- enc_override[[it]]
  if (is.na(enc) || !nzchar(enc))
    stop("read_item('", it, "'): no encoding (not in __ReadMe.xlsx 'Item name' and no enc_override). ",
         "Add a registry row or an enc_override fallback.", call. = FALSE)
  f <- file.path(base, "__Public/comparative-data", paste0(enc, ".tsv"))
  if (!file.exists(f)) stop("read_item('", it, "'): TSV not found -> ", f, call. = FALSE)
  read.table(f, header = TRUE, sep = "\t", stringsAsFactors = FALSE, check.names = FALSE)
}

## ============================================================================================
## 3  Standardized terms (+ per-reference fallback) and paper-specific reshapes
## ============================================================================================
terms <- read.csv("standardized_term_volumes.csv", check.names = FALSE)
# A newly added table may not yet be stacked into standardized_term_volumes.csv (that file is
# rebuilt by standardized_term.R). Rather than force a rebuild of a shared file, read the
# per-reference map directly for any selected item the stacked file does not cover.
for (it in setdiff(select_datasets$item, unique(terms$Reference))) {
  f <- file.path("standardized_term_by_reference", paste0(it, "_standardized_terms.csv"))
  if (!file.exists(f))
    stop("No term map for selected item '", it, "'. Expected rows in standardized_term_volumes.csv ",
         "or the file ", f, call. = FALSE)
  message("Term map: '", it, "' not in standardized_term_volumes.csv -> read ", basename(f),
          " directly (re-run standardized_term.R to stack it permanently).")
  terms <- bind_rows(terms, read.csv(f, check.names = FALSE, fileEncoding = "UTF-8"))
}

# Laterality guard (see README__merging.md "Hemispheres"). laterality_known.csv records, for every
# source column measured from ONE SIDE, which side it was and -- crucially -- WHO did any doubling:
#
#   doubling = none       the printed number is one side AS MEASURED. Its standardized term MUST
#                         carry the laterality suffix (_unilateral/_left/_right) so a one-side value
#                         can never be silently merged/averaged with a both-sides volume. If a
#                         both-sides partner is wanted, THIS MERGE builds it in step 7 and records
#                         `estimated_bilateral_from_unilateral`.
#   doubling = by_source  the PUBLISHED number is already 2x one side -- the paper's authors doubled
#                         it, with a stated symmetry argument (de Sousa 2010 V1/LGN; de Sousa 2013
#                         LGN). It is a deliberate both-sides ESTIMATE, so its term must carry NO
#                         laterality suffix, it is used exactly as published, and it must never be
#                         doubled a second time. Recorded as `published_bilateral_estimate`.
#
# BOTH are PROVENANCE, never vetoes: neither ever drops a value. Vetoes are a different mechanism
# entirely (volumes_select_value_flags.csv, action = skip).
lat_known <- tryCatch(read.csv("laterality_known.csv", stringsAsFactors = FALSE),
                      error = function(e) NULL)
lat_src_doubled <- data.frame(Reference = character(), Standardized_Term = character())
if (!is.null(lat_known) && nrow(lat_known)) {
  if (is.null(lat_known$doubling)) lat_known$doubling <- "none"      # pre-`doubling` registries
  lat_known$doubling[is.na(lat_known$doubling) | !nzchar(lat_known$doubling)] <- "none"
  bad_dbl <- setdiff(unique(lat_known$doubling), c("none", "by_source"))
  if (length(bad_dbl))
    stop("laterality_known.csv: unknown doubling value(s) ", paste(bad_dbl, collapse = ", "),
         ". Use `none` (one side as measured) or `by_source` (published as 2x one side).",
         call. = FALSE)
  lat_known <- lat_known[lat_known$Reference %in% select_datasets$item, , drop = FALSE]
  if (nrow(lat_known)) {
    chk <- merge(lat_known, terms, by = c("Reference", "Original_Term"), all.x = TRUE)
    unmapped <- chk[is.na(chk$Standardized_Term), ]
    if (nrow(unmapped))
      warning("Laterality guard: ", nrow(unmapped), " registered column(s) have no standardized ",
              "term -> ", paste(sprintf("%s:%s", unmapped$Reference, unmapped$Original_Term),
                                collapse = "; "))
    # doubling = none -> the suffix is REQUIRED
    one <- chk[chk$doubling == "none" & !is.na(chk$Standardized_Term), ]
    blank <- one[is.na(one$required_suffix) | !nzchar(one$required_suffix), ]
    if (nrow(blank))                                 # a registry error, not a term-map error
      warning("Laterality guard: ", nrow(blank), " row(s) have doubling=none but no required_suffix ",
              "(a one-side column must declare its suffix; use doubling=by_source if the published ",
              "value already represents both sides) -> ",
              paste(sprintf("%s:%s", blank$Reference, blank$Original_Term), collapse = "; "))
    one <- one[!(is.na(one$required_suffix) | !nzchar(one$required_suffix)), ]
    # Anchored, so the suffix must sit immediately before _Vol.mm3 -- symmetric with the by_source
    # test below, and it catches a suffix in the wrong position rather than anywhere in the string.
    bad <- one[!mapply(function(s, suf) grepl(paste0(suf, "_Vol.mm3$"), s),
                       one$Standardized_Term, one$required_suffix), , drop = FALSE]
    if (nrow(bad))
      warning("Laterality guard: ", nrow(bad), " one-side column(s) missing the required suffix -> ",
              paste(sprintf("%s:%s (want %s, got %s)", bad$Reference, bad$Original_Term,
                            bad$required_suffix, bad$Standardized_Term), collapse = "; "))
    # doubling = by_source -> the published value already represents both sides, suffix FORBIDDEN
    src <- chk[chk$doubling == "by_source" & !is.na(chk$Standardized_Term), ]
    bad2 <- src[grepl("_(unilateral|left|right)_Vol\\.mm3$", src$Standardized_Term), ]
    if (nrow(bad2))
      warning("Laterality guard: ", nrow(bad2), " author-doubled column(s) carry a laterality ",
              "suffix they should not (the published value already represents both sides) -> ",
              paste(sprintf("%s:%s (%s)", bad2$Reference, bad2$Original_Term,
                            bad2$Standardized_Term), collapse = "; "))
    if (!nrow(bad) && !nrow(bad2) && !nrow(unmapped) && !nrow(blank))
      message("Laterality guard OK: ", nrow(one), " one-side column(s) in the selection correctly ",
              "suffixed, ", nrow(src), " author-doubled column(s) correctly unsuffixed.")
    lat_src_doubled <- unique(src[, c("Reference", "Standardized_Term")])  # stamped in step 7b
    # NOTE the registry is filtered to the selection above, so rows for unselected sources are not
    # validated here. Registry-wide validation lives in _checks/check_laterality_doubling.py.
  }
}

nrm <- function(x) tolower(trimws(gsub("\\s+"," ", gsub("[._]"," ", x))))   # species-name normaliser
num <- function(x) suppressWarnings(as.numeric(gsub(",","", as.character(x))))

paper_long <- function(row) {
  it <- row$item; df <- read_item(it); tmap <- terms %>% filter(Reference == it)

  # Canonicalize column headers to the term map's Original_Term spelling up front (TSV headers
  # drift in case/punctuation after re-encoding), then fold a bare species header into "Species".
  .ck <- function(x) tolower(gsub("[ ._]+", "", x))
  .canon <- tmap$Original_Term[match(.ck(names(df)), .ck(tmap$Original_Term))]
  names(df) <- ifelse(is.na(.canon), names(df), .canon)
  .sp0 <- names(df)[tolower(names(df)) %in% c("species", "species name")]
  if (length(.sp0)) names(df)[names(df) == .sp0[1]] <- "Species"

  # --- paper-specific reshapes -----------------------------------------------------------------
  if (it == "Zilles_Rehkämper_1988_Table12-2") {                # structure-rows -> one Pongo row
    z <- df %>% transmute(Species = as.character(Species),      # raw; resolved in step 4
                          Variable = tmap$Standardized_Term[match(structure, tmap$Original_Term)],
                          Value = num(volume_mm3)) %>% filter(!is.na(Variable))
    return(z %>% mutate(Source = it, Team = row$team, Year = row$year, Pick = row$pick))
  }
  if (it == "Bauernfeind_etal_2013_Table1") {                   # per-individual -> species means (Pongo merge), mg->g
    df <- df %>% mutate(lab = ifelse(Species %in% c("Pongo abelii","Pongo pygmaeus"),
                                     "Pongo pygmaeus and Pongo abelii", Species))
    meas <- c("granular_L_mm3","dysgranular_L_mm3","agranular_L_mm3","FI_L_mm3","total_insula_L_mm3","brain_volume_mm3","brain_mass_mg","body_mass_g")
    spm <- df %>% group_by(Species, lab) %>% summarise(across(all_of(meas), ~mean(num(.x), na.rm=TRUE)), .groups="drop")
    df  <- spm %>% group_by(lab) %>% summarise(across(all_of(meas), ~mean(.x, na.rm=TRUE)), .groups="drop") %>%
           mutate(brain_mass_mg = brain_mass_mg/1000) %>% rename(Species = lab)
  }
  if (it == "Bauernfeind_etal_2013_Table2") {                   # per-individual RIGHT insula -> species means (Pongo merge), already mm3
    df <- df %>% mutate(lab = ifelse(Species %in% c("Pongo abelii","Pongo pygmaeus"),
                                     "Pongo pygmaeus and Pongo abelii", Species))
    meas <- c("granular_R_mm3","dysgranular_R_mm3","agranular_R_mm3","FI_R_mm3","total_insula_R_mm3")
    spm <- df %>% group_by(Species, lab) %>% summarise(across(all_of(meas), ~mean(num(.x), na.rm=TRUE)), .groups="drop")
    df  <- spm %>% group_by(lab) %>% summarise(across(all_of(meas), ~mean(.x, na.rm=TRUE)), .groups="drop") %>%
           rename(Species = lab)
  }
  if (it %in% c("MacLeod_etal_2003_Table1", "MacLeod_etal_2003_Table2", "MacLeod_etal_2003_")) {
    meas <- c("cerebellum_volume_cm3","vermis_volume_cm3","hemisphere_volume_cm3","brain_volume_cm3")
    df <- df %>% group_by(Species) %>% summarise(across(all_of(meas), ~mean(num(.x)*1000, na.rm=TRUE)), .groups="drop")
  }
  if (it == "deSousa_etal_2010_Table1")                          # per-specimen hominoid volumes: cm3 -> mm3 (specimens collapse to a species mean in step 5a). V1/LGN are LEFT-only and printed UNDOUBLED (laterality_known.csv, doubling = none); neocortex + whole brain are both-hemisphere. The doubled 2x-left figures are the same paper's Supp. Table 2 (doubling = by_source), not in this selection.
    df <- df %>% mutate(across(ends_with("_cm3"), ~num(.x)*1000))
  if (it == "Smaers_etal_2011_SupplementaryTable1") {            # per-individual TOTAL frontal -> species means of COMBINED L+R (cm3->mm3)
    # GREY ONLY, WHOLE LOBE ONLY (see the selection comment above). `frontal_grey_total_cm3` is
    # already left+right in the printed table, so the *1000 is a pure cm3->mm3 unit change and no
    # bilateral doubling is involved (nothing to record in laterality_known.csv).
    # `frontal_white_total_cm3` is dropped here — NOT in volumes_select_value_flags.csv, because a
    # `skip` row means "this value is unusable"; this is a scope decision, not a data defect. The
    # term-map row for it stays, so volumes_compiled.R still carries frontal white. To bring white
    # into THIS merge, re-add the summarise line below; nothing else needs to change.
    fix <- c("Cercopithecus ascianus"="Cercopithecus ascanius","Cercocebus albigena"="Lophocebus albigena",
             "Procolobus badius"="Piliocolobus badius","Lagothrix lagotricha"="Lagothrix lagothricha")
    df <- df %>% mutate(Species = ifelse(Species %in% names(fix), fix[Species], Species)) %>%
      group_by(Species) %>%
      summarise(frontal_grey_total_cm3  = mean(num(frontal_grey_total_cm3) *1000, na.rm = TRUE), .groups = "drop")
    #   frontal_white_total_cm3 = mean(num(frontal_white_total_cm3)*1000, na.rm = TRUE)  # <- grey-only scope, 2026-08-12
  }
  if (it == "Smaers_etal_2017_TableS1part1") {
    # Species are printed with underscores and, for the apes, as trinomials
    # (Gorilla_gorilla_gorilla, Pan_troglodytes_troglodytes) -> binomial, then the curated
    # overrides in _keys/volumes_species_overrides.csv lump them to Gorilla sp. / Pongo sp.
    # UNITS: Table S1 labels the columns mm3 but the numbers are cm3 — value-matched against
    # Frahm et al. 1984 (Homo primary_visual_gray 14.787 == Frahm area striata grey 14787 mm3;
    # Cercopithecus ascanius 4.272 == 4272; Gorilla 12.062 == 12062). So x1000 here.
    meas <- c("primary_visual_gray","prefrontal_gray","other_association_gray","frontal_motor_gray",
              "primary_visual_white","prefrontal_white","other_association_white","frontal_motor_white")
    meas <- intersect(meas, names(df))
    df <- df %>%
      mutate(Species = word(str_squish(gsub("_", " ", as.character(Species))), 1, 2)) %>%
      group_by(Species) %>%
      summarise(across(all_of(meas), ~ mean(num(.x) * 1000, na.rm = TRUE)), .groups = "drop")
  }
  if (it == "Stephan_etal_1987_Table1")                          # NTO printed "0" = "not determinable with certainty" (data dictionary), not a true zero -> NA
    df <- df %>% mutate(Nucleus_tractus_olfactorius_mm3 =
            ifelse(num(Nucleus_tractus_olfactorius_mm3) == 0, NA_real_, num(Nucleus_tractus_olfactorius_mm3)))

  # --- generic wide -> long via standardized terms ----------------------------------------------
  spcand <- tmap$Original_Term[tmap$Standardized_Term == "Species"]
  spcol  <- spcand[spcand %in% names(df)][1]
  if (is.na(spcol)) spcol <- names(df)[match(TRUE, tolower(names(df)) == "species")]
  if (is.na(spcol)) spcol <- grep("^species", names(df), ignore.case = TRUE, value = TRUE)[1]
  if (is.na(spcol)) stop("paper_long('", it, "'): no species column found. Columns: ",
                         paste(names(df), collapse = ", "), call. = FALSE)
  ckey <- function(x) tolower(gsub("[ ._]+", "", x))
  tkey <- ckey(tmap$Original_Term)
  keep <- names(df)[ckey(names(df)) %in% tkey & names(df) != spcol]
  if (!length(keep))
    stop("paper_long('", it, "'): no measured columns matched the term map. df cols: ",
         paste(names(df), collapse = ", "), call. = FALSE)
  df %>% transmute(Species = as.character(.data[[spcol]]),
                   across(all_of(keep), num)) %>%
    pivot_longer(-Species, names_to="orig", values_to="Value") %>%
    filter(!is.na(Value)) %>%
    mutate(Variable = tmap$Standardized_Term[match(ckey(orig), tkey)],
           Source = it, Team = row$team, Year = row$year, Pick = row$pick) %>%
    select(Species, Variable, Value, Source, Team, Year, Pick)
}
long <- bind_rows(lapply(seq_len(nrow(select_datasets)),
                         function(i) paper_long(select_datasets[i, ])))
message("Read ", nrow(select_datasets), " selected table(s) -> ", nrow(long), " raw value(s).")

## ============================================================================================
## 4  Species resolution: NCBI backbone + curated, source-aware overrides
## ============================================================================================
## Identical to volumes_compiled.R §4: curated project decisions WIN over NCBI; resolution is
## SOURCE-AWARE (overrides keyed by Reference + raw variant); a reviewable mapping table is written.
raw  <- long %>% distinct(Source, Species) %>% rename(Species_raw = Species)
uniq <- sort(unique(raw$Species_raw))

cache_file <- "volumes_species_ids_cache.csv"
have_taxizedb <- suppressWarnings(requireNamespace("taxizedb", quietly = TRUE))
ncbi_live <- if (have_taxizedb) tryCatch({
  library(taxizedb)
  ids <- name2taxid(uniq, out_type = "summary")
  nm  <- tibble(Species_raw = uniq, NCBI_id = ids$id[match(uniq, ids$name)])
  nv  <- taxid2name(unique(na.omit(nm$NCBI_id)), out_type = "summary")
  names(nv) <- unique(na.omit(nm$NCBI_id))
  nm %>% mutate(NCBI_name = unname(nv[as.character(NCBI_id)]))
}, error = function(e) { message("taxizedb live resolution failed (", conditionMessage(e),
                                 ") -> using cache ", cache_file); NULL }) else {
  message("taxizedb not installed -> using NCBI backbone cache ", cache_file); NULL }
if (is.null(ncbi_live)) {
  if (!file.exists(cache_file))
    stop("Offline species resolution needs ", cache_file, " (taxizedb unavailable and no cache). ",
         "Run once with taxizedb installed to build it.", call. = FALSE)
  cache <- read.csv(cache_file, stringsAsFactors = FALSE, na.strings = c("NA", ""))
  ncbi  <- cache %>% mutate(NCBI_name = ifelse(is.na(NCBI_name) | !nzchar(NCBI_name), NA_character_, NCBI_name)) %>%
    distinct(Species_raw, NCBI_id, NCBI_name)
  miss  <- setdiff(uniq, ncbi$Species_raw)
  # This script exists to try out selections, so a name the cache has never seen is a WARNING (the
  # raw name is kept and flagged) rather than a hard stop. Refresh the cache with a live taxizedb
  # run, or add a curated override, to clear it.
  if (length(miss))
    warning("NCBI backbone cache ", cache_file, " is missing ", length(miss), " raw name(s) -> kept ",
            "raw and flagged: ", paste(head(miss, 12), collapse = "; "))
  ncbi <- tibble(Species_raw = uniq) %>% left_join(ncbi, by = "Species_raw")
} else {
  ncbi <- ncbi_live
}

ov <- read.csv(file.path(base, "_keys/volumes_species_overrides.csv"), stringsAsFactors = FALSE) %>%
  transmute(Source = Reference, key = nrm(variant_name), curated = accepted_name) %>%
  distinct(Source, key, .keep_all = TRUE)

resolved <- raw %>%
  mutate(key = nrm(Species_raw)) %>%
  left_join(ov,   by = c("Source", "key")) %>%
  left_join(ncbi, by = "Species_raw") %>%
  mutate(Species_final = dplyr::coalesce(curated, NCBI_name, Species_raw),
         name_source   = dplyr::case_when(!is.na(curated)   ~ "curated",
                                          !is.na(NCBI_name) ~ "NCBI",
                                          TRUE              ~ "unresolved_raw"),
         flag_curated_overrides_ncbi = !is.na(curated) & !is.na(NCBI_name) & nrm(curated) != nrm(NCBI_name),
         flag_unresolved             = is.na(curated) & is.na(NCBI_name)) %>%
  select(-key)
write_csv(resolved %>% arrange(Source, Species_raw), sel_csv("volumes_source_species_ids"))
if (any(resolved$flag_unresolved))
  warning("Species resolution: ", sum(resolved$flag_unresolved), " (source, name) pair(s) had no ",
          "curated override and no NCBI match -> kept raw. See ",
          sel_csv("volumes_source_species_ids"), ".")
# NOTE: unlike volumes_compiled.R this script never rewrites volumes_species_ids_cache.csv — the
# cache is the full merge's artefact and a partial selection must not shrink it.

long <- long %>%
  left_join(resolved %>% select(Source, Species_raw, Species_final),
            by = c("Source", "Species" = "Species_raw")) %>%
  mutate(Species = Species_final) %>% select(-Species_final)

## ============================================================================================
## 4b  Taxon filter (see `taxa_keep` in the options block)
## ============================================================================================
## Applied here, straight after resolution, so every downstream artefact — long, wide, flags,
## audit, README — describes the same set of species. A species is matched on its accepted name;
## if that is not in the registry, its GENUS is tried, which catches labels the registry has not
## caught up with. Anything still unmatched is handled by `taxa_unmatched`.
taxonomy <- read.csv(file.path(base, "_keys", "species_taxonomy.csv"), stringsAsFactors = FALSE)
if (!taxa_rank %in% names(taxonomy))
  stop("taxa_rank = '", taxa_rank, "' is not a column of _keys/species_taxonomy.csv (have: ",
       paste(names(taxonomy), collapse = ", "), ").", call. = FALSE)
taxon_excluded <- tibble(Species = character(), Order = character(), Family = character(),
                         reason = character(), n_values = integer(), Sources = character())
if (identical(taxa_keep, "all")) {
  message("Taxon filter: off (taxa_keep = \"all\").")
} else {
  genus  <- function(x) sub("^([A-Za-z]+).*$", "\\1", x)
  by_sp  <- setNames(taxonomy[[taxa_rank]], taxonomy$Species)
  # genus -> rank, only where a genus maps unambiguously to one value
  gtab   <- unique(data.frame(g = genus(taxonomy$Species), v = taxonomy[[taxa_rank]]))
  gtab   <- gtab[!(gtab$g %in% gtab$g[duplicated(gtab$g)]), ]
  by_gen <- setNames(gtab$v, gtab$g)

  spp  <- sort(unique(long$Species))
  rank_of <- unname(ifelse(!is.na(by_sp[spp]), by_sp[spp], by_gen[genus(spp)]))
  matched <- !is.na(rank_of)
  keep_sp <- spp[matched & rank_of %in% taxa_keep]
  drop_sp <- spp[matched & !(rank_of %in% taxa_keep)]
  unmatched_sp <- spp[!matched]

  if (length(unmatched_sp)) {
    msg <- paste0(length(unmatched_sp), " species not in _keys/species_taxonomy.csv (nor resolvable ",
                  "by genus): ", paste(head(unmatched_sp, 12), collapse = "; "))
    if (taxa_unmatched == "stop")
      stop("Taxon filter: ", msg, ". Add them to the registry, or set taxa_unmatched.", call. = FALSE)
    warning("Taxon filter: ", msg, " -> ", if (taxa_unmatched == "drop") "DROPPED" else "kept",
            " (taxa_unmatched = '", taxa_unmatched, "'). See ", sel_csv("volumes_taxon_excluded"), ".")
    if (taxa_unmatched == "keep") keep_sp <- c(keep_sp, unmatched_sp)
  }

  gone <- long %>% filter(!(Species %in% keep_sp)) %>%
    group_by(Species) %>%
    summarise(n_values = n(), Sources = paste(sort(unique(Source)), collapse = "; "), .groups = "drop")
  taxon_excluded <- gone %>%
    left_join(taxonomy, by = "Species") %>%
    mutate(reason = ifelse(Species %in% unmatched_sp,
                           "not in species_taxonomy.csv", paste0("not in taxa_keep (", taxa_rank, ")"))) %>%
    select(Species, Order, Family, reason, n_values, Sources) %>%
    arrange(reason, Species)

  long <- long %>% filter(Species %in% keep_sp)
  message("Taxon filter: keeping ", taxa_rank, " ", paste(taxa_keep, collapse = "/"), " -> ",
          length(keep_sp), " species kept, ", nrow(taxon_excluded), " excluded (",
          sum(taxon_excluded$reason != "not in species_taxonomy.csv"), " out of scope, ",
          sum(taxon_excluded$reason == "not in species_taxonomy.csv"), " unregistered).")
  if (!nrow(long))
    stop("Taxon filter removed every row — check taxa_keep/taxa_rank spelling against ",
         "_keys/species_taxonomy.csv.", call. = FALSE)
}
write_csv(taxon_excluded, sel_csv("volumes_taxon_excluded"))

write_csv(long, sel_csv("volumes_unfiltered"))
is_mass <- function(v) v %in% c("Body_Mass.g","Brain_Mass.mg")

## ============================================================================================
## 5a  Collapse each SOURCE to one value per species x structure
## ============================================================================================
## Per-specimen tables (de Sousa 2010) and tables that list the same species twice are averaged
## WITHIN the source first, so the recency comparison in 5b is table-vs-table, never row-vs-row.
cand <- long %>%
  group_by(Species, Variable, Source, Team, Year, Pick) %>%
  summarise(Value = mean(Value, na.rm = TRUE), n_obs = n(), .groups = "drop")

## ============================================================================================
## 5b  Value flags — a `skip` removes a candidate BEFORE the recency pick
## ============================================================================================
## Registry columns: Source, Species, Variable, flag, action, reason, evidence.
##   Source / Species / Variable : exact value, "*" (or blank) for all, or a trailing-"*" prefix
##                                 match, e.g. "Area_striata_*".
##   action : skip   = never use this value, however recent (reported in the README)
##            review = use it, but list it in the README as needing eyes
##            keep   = explicitly un-skip (use to carve an exception out of a broader skip row)
## The MOST SPECIFIC matching row wins (Source > Species > Variable); among equally specific rows
## the one LAST in the file wins. Edit the CSV, not this script.
vflags <- if (file.exists(flags_file)) {
  read.csv(flags_file, stringsAsFactors = FALSE, na.strings = c("NA",""), fileEncoding = "UTF-8")
} else {
  message("No ", flags_file, " -> no value flags applied.")
  data.frame(Source=character(), Species=character(), Variable=character(),
             flag=character(), action=character(), reason=character(), evidence=character())
}
for (cl in c("Source","Species","Variable","flag","action","reason","evidence"))
  if (is.null(vflags[[cl]])) vflags[[cl]] <- NA_character_
vflags <- vflags %>%
  mutate(across(c(Source, Species, Variable), ~ ifelse(is.na(.x) | !nzchar(trimws(.x)), "*", trimws(.x))),
         action = tolower(ifelse(is.na(action) | !nzchar(trimws(action)), "review", trimws(action))),
         .row = row_number())
bad_action <- setdiff(vflags$action, c("skip","review","keep"))
if (length(bad_action))
  stop(flags_file, ": unknown action(s) ", paste(unique(bad_action), collapse=", "),
       " — use skip / review / keep.", call. = FALSE)

.pat_match <- function(pat, x) {
  if (pat == "*") return(rep(TRUE, length(x)))
  if (grepl("\\*$", pat)) return(startsWith(x, sub("\\*$", "", pat)))
  x == pat
}
cand$flag <- NA_character_; cand$action <- "use"; cand$flag_reason <- NA_character_
cand$flag_evidence <- NA_character_; cand$.spec <- -1L; cand$.row <- NA_integer_
vflags$hits <- 0L
for (i in seq_len(nrow(vflags))) {
  f <- vflags[i, ]
  hit <- .pat_match(f$Source, cand$Source) & .pat_match(f$Species, cand$Species) &
         .pat_match(f$Variable, cand$Variable)
  vflags$hits[i] <- sum(hit)
  spec <- 4L*(f$Source != "*") + 2L*(f$Species != "*") + 1L*(f$Variable != "*")
  take <- hit & (spec >= cand$.spec)          # >= so a later, equally specific row wins
  cand$flag[take] <- f$flag; cand$action[take] <- f$action
  cand$flag_reason[take] <- f$reason; cand$flag_evidence[take] <- f$evidence
  cand$.spec[take] <- spec; cand$.row[take] <- f$.row
}
cand$action[cand$action == "keep"] <- "use"    # `keep` = an explicit un-skip
stale <- vflags %>% filter(hits == 0)
if (nrow(stale))
  message("Value-flag registry: ", nrow(stale), " row(s) matched nothing in this selection ",
          "(listed in the README as stale).")

## ============================================================================================
## 5c  Resolve WITHIN each team: most recent unflagged value wins
## ============================================================================================
usable <- cand %>% filter(action != "skip") %>%
  mutate(.tiekey = if (tie_rule == "last") -Pick else Pick)
teamres <- usable %>%
  arrange(Species, Variable, Team, desc(Year), .tiekey) %>%   # newest first, tie-break by `pick`
  group_by(Species, Variable, Team) %>%
  mutate(.top = Year == first(Year)) %>%                      # the newest year's row(s)
  summarise(n_tied = sum(.top),
            Value  = if (tie_rule == "mean" && sum(.top) > 1) mean(Value[.top]) else first(Value),
            Source = if (tie_rule == "mean" && sum(.top) > 1)
                       paste(sort(Source[.top]), collapse = " + ") else first(Source),
            Year   = first(Year),                             # keep last: earlier lines need raw Year
            .groups = "drop")

# Mass exception (see README__merging.md): body/brain weight are specimen attributes that later
# papers re-use rather than re-measure, so pin them to the reference tables and let other sources
# only fill gaps.
if (mass_rule == "reference") {
  massref <- usable %>% filter(is_mass(Variable), grepl(mass_reference_pattern, Source)) %>%
    group_by(Species, Variable, Team) %>%
    summarise(Value = first(Value), Year = first(Year), Source = first(Source), n_tied = 1L,
              .groups = "drop")
  teamres <- teamres %>%
    anti_join(massref %>% distinct(Species, Variable, Team), by = c("Species","Variable","Team")) %>%
    bind_rows(massref)
}

## ============================================================================================
## 6  Across teams: average (no-op when the selection uses a single team)
## ============================================================================================
n_teams_used <- n_distinct(select_datasets$team)
volumes_long <- teamres %>% group_by(Species, Variable) %>% summarise(
  # mass under `reference`: no cross-team average — take the team whose winning source IS a mass
  # reference table, else the first team.
  keep_i  = if (is_mass(first(Variable)) && mass_rule == "reference")
              which.max(grepl(mass_reference_pattern, Source)) else NA_integer_,
  Value   = if (is.na(keep_i)) mean(Value) else Value[keep_i],
  Teams   = if (is.na(keep_i)) paste(sort(unique(Team)), collapse = "; ") else Team[keep_i],
  n_teams = if (is.na(keep_i)) n_distinct(Team) else 1L,
  # `Sources` is always a "; " list of INDIVIDUAL item names. tie_rule = "mean" can write "A + B"
  # into Source, so split before re-collapsing or the exploded contributions table below would carry
  # "A + B" as though it were one uncitable item. Mirrors step 6 of volumes_compiled.R.
  Sources = { s <- if (is.na(keep_i)) Source else Source[keep_i]
              paste(sort(unique(trimws(unlist(strsplit(s, " + ", fixed = TRUE))))), collapse = "; ") },
  n_sources = { s <- if (is.na(keep_i)) Source else Source[keep_i]
                n_distinct(trimws(unlist(strsplit(s, " + ", fixed = TRUE)))) },
  # which team contributed which table -- `Teams` is a lab/collection grouping, not a reference
  Source_detail = { i <- if (is.na(keep_i)) order(Team) else keep_i
                    paste(paste0(Team[i], ": ", Source[i]), collapse = " | ") },
  Year_used = if (is.na(keep_i)) max(Year) else Year[keep_i],
  .groups = "drop") %>%
  select(-keep_i) %>%
  arrange(Species, Variable)

## ============================================================================================
## 6b  The report: what the flags cost us
## ============================================================================================
used_year <- teamres %>% select(Species, Variable, Team, Year_used = Year, Source_used = Source)
skipped <- cand %>% filter(action == "skip") %>%
  left_join(used_year, by = c("Species","Variable","Team")) %>%
  mutate(outcome = case_when(
           is.na(Year_used)      ~ "dropped — no other source covers this cell",
           Year > Year_used      ~ "more recent than the value used",
           Year == Year_used     ~ "same year as the value used",
           TRUE                  ~ "older than the value used"),
         more_recent = is.na(Year_used) | Year >= Year_used) %>%
  select(Species, Variable, Team, Source_skipped = Source, Year_skipped = Year,
         Value_skipped = Value, flag, reason = flag_reason, evidence = flag_evidence,
         Source_used, Year_used, outcome, more_recent) %>%
  arrange(desc(more_recent), Source_skipped, Variable, Species)
write_csv(skipped, sel_csv("volumes_flagged_not_used"))

reviewed <- teamres %>%
  inner_join(cand %>% filter(action == "review") %>%
               select(Species, Variable, Team, Source, flag, flag_reason, flag_evidence),
             by = c("Species","Variable","Team","Source")) %>%
  arrange(Variable, Species)
ties <- teamres %>% filter(n_tied > 1) %>% arrange(Variable, Species)

# Full audit: every candidate, whether it was used, superseded or skipped.
audit <- cand %>%
  left_join(used_year, by = c("Species","Variable","Team")) %>%
  mutate(status = case_when(action == "skip"          ~ "skipped (flagged)",
                            Source == Source_used     ~ "USED",
                            # tie_rule = "mean" writes "A + B" into Source_used
                            str_detect(coalesce(Source_used, ""), fixed(Source)) ~ "USED (tied, averaged)",
                            TRUE                      ~ "superseded (older)")) %>%
  select(Species, Variable, Team, Source, Year, Value, n_obs, status, flag, action,
         Source_used, Year_used, reason = flag_reason) %>%
  arrange(Species, Variable, desc(Year))
write_csv(audit, sel_csv("volumes_resolution_audit"))

## ============================================================================================
## 7  Hemisphere reconciliation -> whole-structure both-hemisphere volumes
## ============================================================================================
## See README__merging.md "Hemispheres". both sides measured -> SUM; one side only -> 2x, flagged.
flags <- tibble(Species=character(), Variable=character(), flag=character(), detail=character())
if (do_hemisphere_reconciliation) {
  wide_v <- volumes_long %>% select(Species, Variable, Value) %>%
    pivot_wider(names_from = Variable, values_from = Value)
  mk <- function(stem) c(left = paste0(stem, "_left_Vol.mm3"),
                         right = paste0(stem, "_right_Vol.mm3"),
                         both = paste0(stem, "_Vol.mm3"))
  stems <- if (identical(bilateral_stems, "auto"))
             unique(sub("_(left|right)_Vol\\.mm3$", "",
                        grep("_(left|right)_Vol\\.mm3$", names(wide_v), value = TRUE)))
           else bilateral_stems
  stems <- setdiff(stems, bilateral_stems_exclude)
  message("Step 7 both-sides stems: ", paste(stems, collapse = ", "),
          if (length(bilateral_stems_exclude)) paste0(" | excluded: ",
              paste(bilateral_stems_exclude, collapse = ", ")) else "")
  unil_cols <- grep("_unilateral_Vol\\.mm3$", names(wide_v), value = TRUE)
  getcol <- function(nm) if (nm %in% names(wide_v)) wide_v[[nm]] else rep(NA_real_, nrow(wide_v))

  bilat <- list()
  for (st in stems) {                                        # left (+right) -> both
    m <- mk(st); L <- getcol(m["left"]); R <- getcol(m["right"])
    both <- ifelse(!is.na(L) & !is.na(R), L + R,
            ifelse(!is.na(L), 2*L, ifelse(!is.na(R), 2*R, NA_real_)))
    est  <- xor(!is.na(L), !is.na(R))                        # only one side present -> doubled
    src  <- ifelse(!is.na(L), m["left"], m["right"])
    k <- !is.na(both)
    bilat[[unname(m["both"])]] <- tibble(Species = wide_v$Species[k], Variable = unname(m["both"]),
                                         Value = both[k], est = est[k], src = src[k])
  }
  for (uv in unil_cols) {                                    # one side only -> 2x (flagged)
    bv <- sub("_unilateral_Vol\\.mm3$", "_Vol.mm3", uv); U <- getcol(uv); k <- !is.na(U)
    bilat[[bv]] <- tibble(Species = wide_v$Species[k], Variable = bv, Value = 2*U[k],
                          est = TRUE, src = uv)
  }
  bilat <- bind_rows(bilat)
  if (nrow(bilat)) {
    # a real both-sides value always beats a doubled estimate
    bilat <- bilat %>% anti_join(volumes_long %>% distinct(Species, Variable),
                                 by = c("Species","Variable"))
    # A derived both-sides value inherits the provenance of the one-side variable it was built from --
    # that is the paper a reader must cite for it, even though the arithmetic happened here.
    src_meta <- volumes_long %>% transmute(Species, src = Variable, Teams, n_teams,
                                           Sources, n_sources, Source_detail, Year_used)
    volumes_long <- bind_rows(volumes_long,
      bilat %>% left_join(src_meta, by = c("Species","src")) %>%
        transmute(Species, Variable, Value, Teams, n_teams,
                  Sources, n_sources, Source_detail, Year_used)) %>%
      arrange(Species, Variable)
    flags <- bind_rows(flags, bilat %>% filter(est) %>%
      transmute(Species, Variable, flag = "estimated_bilateral_from_unilateral",
                detail = paste0("both-hemisphere estimated as 2x ", src, " (only one side measured)")))
  }
}

## ---- 7b  Provenance for the OTHER kind of doubling --------------------------------------------
## Values whose PUBLISHED figure is already 2x one side. Not a veto -- the value is used exactly as
## published; this only records that the both-sides number is an author-side estimate rather than a
## both-sides measurement, so it is never doubled again and so anyone comparing it to a truly
## bilateral measurement knows what they are holding. Stamped on the values actually USED (teamres),
## joined by the winning source.
if (nrow(lat_src_doubled)) {
  # `tie_rule = "mean"` can write "A + B" into Source. Split on that separator and match EXACTLY:
  # item names here are prefix-nested (Stephan_etal_1981_TableI is a substring of ..._TableIII), so
  # substring matching would mis-attribute the moment a Stephan table is registered `by_source`.
  .doubled_ref <- function(variable, source) {
    refs <- lat_src_doubled$Reference[lat_src_doubled$Standardized_Term == variable]
    hit  <- intersect(refs, trimws(strsplit(source, "+", fixed = TRUE)[[1]]))
    if (length(hit)) paste(sort(hit), collapse = " + ") else NA_character_
  }
  pubdbl <- teamres %>%
    filter(Variable %in% lat_src_doubled$Standardized_Term) %>%
    # vapply, not mapply: mapply returns list() on zero rows, which makes .ref a list-column.
    mutate(.ref = vapply(seq_len(n()),
                         function(i) .doubled_ref(Variable[i], Source[i]), character(1))) %>%
    filter(!is.na(.ref)) %>%
    distinct(Species, Variable, .ref) %>%
    # A one-team selection needs no caveat, but step 6 averages across teams whenever the selection
    # names more than one -- and then the merged number is a mean the doubled source contributed to,
    # not itself 2x one hemisphere. Say which, so the flag can never overclaim. (Mirrors 7b in
    # volumes_compiled.R, which is always multi-team.)
    left_join(volumes_long %>% select(Species, Variable, Teams, n_teams),
              by = c("Species", "Variable")) %>%
    transmute(Species, Variable, flag = "published_bilateral_estimate",
              detail = ifelse(
                coalesce(n_teams, 1L) > 1L,
                paste0("a contributing source publishes its figure as 2x one hemisphere, doubled ",
                       "by the source (not by this merge): ", .ref, "; the merged value is the ",
                       "mean across ", n_teams, " teams (", Teams, ") -- see laterality_known.csv"),
                paste0("published value is 2x one hemisphere, doubled by the source (not by ",
                       "this merge): ", .ref, " -- see laterality_known.csv")))
  flags <- bind_rows(flags, pubdbl)
}

## ============================================================================================
## 8  Outputs
## ============================================================================================
write_csv(volumes_long, sel_csv("volumes_long"))
write_csv(flags, sel_csv("volumes_flags"))
volumes_wide <- volumes_long %>%
  pivot_wider(id_cols = Species, names_from = Variable, values_from = Value) %>% arrange(Species)
write_csv(volumes_wide, sel_csv("volumes_wide"))
long %>% group_by(Species_Name = Species) %>%
  summarise(n_sources = n_distinct(Source), Sources = paste(sort(unique(Source)), collapse = "; ")) %>%
  write_csv(sel_csv("volumes_species_sources"))

## ---- 8b Publication provenance: contributions + citations ------------------------------------
## volumes_long_select.csv collapses provenance into strings to stay one row per species x variable.
## These two files are the un-collapsed form, which is what a supplementary source table needs:
##   volumes_source_contributions_select.csv  one row per species x variable x CONTRIBUTING TABLE
##   volumes_source_citations_select.csv      item name -> APA citation, DOI/ISBN, WHICH TABLE
## Mirrors step 8b of volumes_compiled.R. Sources that lost the recency pick, or were vetoed by the
## value-flag registry, are NOT here -- they are the subject of volumes_resolution_audit_select.csv
## and volumes_flagged_not_used_select.csv; this file is only what the published number rests on.
contrib <- volumes_long %>%
  select(Species, Variable, merged_Value = Value, Sources, Teams, n_teams, n_sources, Year_used) %>%
  separate_longer_delim(Sources, delim = "; ") %>%
  rename(Source = Sources) %>%
  # per-source values come from `usable` (the candidates that survived the flag registry), so the
  # figures here are the ones the merge actually saw -- never re-derived from the merged value.
  left_join(usable %>% select(Species, Variable, Source, Team, Year,
                             source_Value = Value, n_rows_in_source = n_obs),
            by = c("Species","Variable","Source")) %>%
  mutate(role = case_when(
           # step 7's both-sides variables are arithmetic on a one-side table, which prints no figure
           # for this term: source_Value is legitimately absent, not missing data.
           is.na(source_Value) ~ paste0("derived both-hemisphere value (step 7: left+right, or 2x a ",
                                        "one-side measurement); cite this source for the one-side figure"),
           is_mass(Variable) & mass_rule == "reference"
                            ~ "reference table used (mass rule: other sources not averaged in)",
           n_sources == 1L  ~ "sole source",
           TRUE             ~ "averaged into the merged value"),
         pct_diff_from_merged = ifelse(!is.na(source_Value) & merged_Value != 0,
                                       round(100 * (source_Value - merged_Value) / merged_Value, 2),
                                       NA_real_)) %>%
  select(Species, Variable, Source, Team, Year, source_Value, merged_Value,
         pct_diff_from_merged, role, n_rows_in_source, Teams, n_teams, n_sources, Year_used) %>%
  arrange(Species, Variable, Source)
source(file.path(folder, "source_citations.R"))
citations <- source_citations(base, unique(c(long$Source, contrib$Source)))
write_csv(citations, sel_csv("volumes_source_citations"))
contrib <- contrib %>%
  left_join(citations %>% select(Source, Cited_as, DOI_or_ISBN), by = "Source") %>%
  relocate(Cited_as, DOI_or_ISBN, .after = Source)
write_csv(contrib, sel_csv("volumes_source_contributions"))
message("Provenance: ", nrow(contrib), " species x variable x source contribution(s) from ",
        nrow(citations), " citable source table(s); ",
        sum(is.na(citations$Citation)), " without a registry citation.")

## ============================================================================================
## 9  Generate README__volumes_compiled_select.md
## ============================================================================================
## GENERATED, so the "flagged values not used" list can never go stale. Hand-written prose belongs
## in README__volumes_compiled_select.INTRO.md (spliced in below) or in the `reason` column of
## volumes_select_value_flags.csv (which is what fills the tables here).
md_esc  <- function(x) gsub("\\|", "\\\\|", ifelse(is.na(x), "", as.character(x)))
md_tbl  <- function(df, header) {
  if (!nrow(df)) return("_none_")
  df <- df %>% mutate(across(everything(), as.character))   # stop apply()'s as.matrix from padding
  c(paste0("| ", paste(header, collapse = " | "), " |"),
    paste0("|", paste(rep("---", length(header)), collapse = "|"), "|"),
    unname(apply(df, 1, function(r) paste0("| ", paste(md_esc(r), collapse = " | "), " |"))))
}
fmtv <- function(x) formatC(x, format = "fg", digits = 6, big.mark = "")

L <- c(
  paste0("<!-- GENERATED by volumes_compiled_select.R on ", format(Sys.time(), "%Y-%m-%d %H:%M"),
         " — do not hand-edit. Put prose in ", readme_intro, ", put flag notes in ", flags_file, ". -->"),
  "", "# Select volume merge — `volumes_compiled_select.R`", "",
  paste0("**Selection:** ", selection_name),
  paste0("**Tables:** ", nrow(select_datasets), " | **Teams:** ", n_teams_used,
         " | **Result:** ", nrow(volumes_wide), " species x ", ncol(volumes_wide) - 1, " variables",
         " | **Tie rule:** `", tie_rule, "` | **Mass rule:** `", mass_rule, "`",
         " | **Taxa:** ", if (identical(taxa_keep, "all")) "all (no filter)"
                          else paste0("`", taxa_rank, " = ", paste(taxa_keep, collapse = ", "), "`")), "")
if (file.exists(readme_intro))
  L <- c(L, readLines(readme_intro, warn = FALSE, encoding = "UTF-8"), "")
L <- c(L,
  "## The rule", "",
  "Every selected table is collapsed to one value per species x structure, then resolved **within a",
  "team by most recent year**. A candidate flagged `skip` in `volumes_select_value_flags.csv` is",
  "removed **before** that pick, so the next-most-recent unflagged value wins instead. Across teams",
  "(only if the selection names more than one) surviving values are averaged, as in `volumes_compiled.R`.",
  "",
  "## Flagged values NOT used — even though they are the most recent", "",
  "These are the values a naive most-recent-wins pass would have taken. Each was vetoed by a `skip`",
  paste0("row in `", flags_file, "`. Full per-species detail: `", sel_csv("volumes_flagged_not_used"), "`."), "")

grp <- skipped %>% filter(more_recent) %>%
  mutate(repl_row = ifelse(is.na(Source_used), "— variable dropped from the merge",
                           paste0(Source_used, " (", Year_used, ")"))) %>%
  group_by(Source_skipped, Year_skipped, Variable, flag) %>%
  summarise(n = n(), repl = paste(sort(unique(repl_row)), collapse = "; "),
            reason = first(reason), evidence = first(evidence),
            detail = paste0(Species, " ", fmtv(Value_skipped), collapse = ", "),
            .groups = "drop") %>% arrange(Variable)
L <- c(L, md_tbl(grp %>% transmute(Source = Source_skipped, Year = Year_skipped, Variable,
                                   Flag = flag, `n values` = n, `Used instead` = repl),
                 c("Source","Year","Variable","Flag","n values","Used instead")), "")
for (i in seq_len(nrow(grp))) {
  g <- grp[i, ]
  L <- c(L, paste0("**`", g$Variable, "`** — ", g$n, " value(s) from `", g$Source_skipped,
                   "` (", g$Year_skipped, "), flag `", g$flag, "`"), "",
         paste0("> ", g$reason), "",
         paste0("_Evidence:_ ", g$evidence, "  "),
         paste0("_Not used:_ ", g$detail), "")
}
sk_old <- skipped %>% filter(!more_recent)
if (nrow(sk_old))
  L <- c(L, "### Flagged values skipped that were NOT the most recent", "",
         "(Vetoed too, but an equally recent or newer unflagged value existed anyway.)", "",
         md_tbl(sk_old %>% transmute(Source = Source_skipped, Year = Year_skipped, Variable, Species,
                                     Flag = flag,
                                     `Used instead` = paste0(Source_used, " (", Year_used, ")")),
                c("Source","Year","Variable","Species","Flag","Used instead")), "")
L <- c(L, "## Values used but flagged `review`", "",
  "Kept in the merge, but the registry says they need eyes.", "")
rv <- reviewed %>% group_by(flag, flag_reason) %>%
  summarise(n = n(), Sources = paste(sort(unique(Source)), collapse = ", "),
            Variables = paste(sort(unique(Variable)), collapse = ", "),
            Species = paste(sort(unique(Species)), collapse = ", "), .groups = "drop")
for (i in seq_len(nrow(rv))) {
  g <- rv[i, ]
  L <- c(L, paste0("**`", g$flag, "`** — ", g$n, " value(s)"), "",
         paste0("> ", g$flag_reason), "",
         paste0("_Sources:_ ", g$Sources, "  "),
         paste0("_Variables:_ ", g$Variables, "  "),
         paste0("_Species:_ ", g$Species), "")
}
if (!nrow(rv)) L <- c(L, "_none_", "")
L <- c(L, "## Same-year ties", "",
  paste0("Two selected tables share a year and both cover the cell. Resolved by ",
         "`tie_rule = \"", tie_rule, "\"` (position in `select_datasets`)."), "")
ti <- ties %>% group_by(Variable, `Winning source` = Source, Year) %>%
  summarise(`n species` = n(), Species = paste(sort(unique(Species)), collapse = ", "),
            .groups = "drop") %>% arrange(Variable)
L <- c(L, md_tbl(ti, names(ti)), "",
  "## Stale flag-registry rows", "",
  "Rows in the registry that matched no candidate in this selection — either the source is not",
  "selected, or the Source/Species/Variable spelling has drifted.", "")
st <- stale %>% transmute(Source, Species, Variable, flag, action)
L <- c(L, md_tbl(st, names(st)), "",
  "## Taxon filter", "")
if (identical(taxa_keep, "all")) {
  L <- c(L, "_Off — `taxa_keep <- \"all\"`, so every species the sources cover is merged._", "")
} else {
  L <- c(L,
    paste0("Keeping `", taxa_rank, "` = ", paste0("**", taxa_keep, "**", collapse = ", "),
           ", per `_keys/species_taxonomy.csv` (matched on the accepted name, falling back to the ",
           "genus). Unmatched species: `taxa_unmatched = \"", taxa_unmatched, "\"`."),
    paste0(nrow(volumes_wide), " species kept, ", nrow(taxon_excluded),
           " excluded — full list with sources in `", sel_csv("volumes_taxon_excluded"), "`."), "",
    md_tbl(taxon_excluded %>%
             group_by(reason, Order) %>%
             summarise(`n species` = n(), Species = paste(sort(Species), collapse = ", "),
                       .groups = "drop") %>%
             arrange(reason, Order),
           c("reason", "Order", "n species", "Species")), "")
}
L <- c(L, "## Hemisphere reconciliation (step 7)", "")
.n_flag <- function(f) sum(flags$flag == f)
# Step 7 (this merge doubling a measured side) can be switched off; step 7b (recording that a SOURCE
# published its figure already doubled) always runs, so its sentence lives outside the else branch.
L <- c(L, if (!do_hemisphere_reconciliation) "_switched off (`do_hemisphere_reconciliation <- FALSE`)._" else c(
  paste0("Both-sides partners built for: ", paste0("`", stems, "`", collapse = ", "), "."),
  if (length(bilateral_stems_exclude))
    paste0("Excluded by `bilateral_stems_exclude`: ", paste0("`", bilateral_stems_exclude, "`", collapse = ", "),
           ".") else NULL,
  paste0("`", .n_flag("estimated_bilateral_from_unilateral"), "` value(s) are 2x estimates from a ",
         "single measured side, doubled **by this merge** (flag ",
         "`estimated_bilateral_from_unilateral` in `", sel_csv("volumes_flags"), "`).")), "",
  paste0("`", .n_flag("published_bilateral_estimate"), "` value(s) arrive **already doubled by the ",
         "source** — the authors published 2x one hemisphere with a stated symmetry argument, so ",
         "the figure is used as published and never doubled again (flag ",
         "`published_bilateral_estimate`; registered as `doubling = by_source` in ",
         "`laterality_known.csv`)."), "",
  paste0("Neither flag is a veto. Both record how a both-sides number came to exist; a value is ",
         "only ever removed by an `action = skip` row in `", flags_file, "`."), "",
  "## Selection", "")
se <- select_datasets %>%
  left_join(cand %>% group_by(Source) %>%
              summarise(cells = n(), used = sum(action != "skip"), .groups = "drop"),
            by = c("item" = "Source")) %>%
  transmute(`#` = pick, Item = item, Team = team, Year = year,
            `species x structure cells` = ifelse(is.na(cells), 0L, cells),
            `not skipped` = ifelse(is.na(used), 0L, used))
L <- c(L, md_tbl(se, names(se)), "",
  "## Files written", "",
  paste0("- `", sel_csv("volumes_long"), "` — merged long table (the result)"),
  paste0("- `", sel_csv("volumes_wide"), "` — species x variable matrix"),
  paste0("- `", sel_csv("volumes_flags"), "` — bilateral-estimate provenance from steps 7 and 7b ",
         "(`estimated_bilateral_from_unilateral`, `published_bilateral_estimate`); neither is a veto"),
  paste0("- `", sel_csv("volumes_unfiltered"), "` — every value read, before resolution"),
  paste0("- `", sel_csv("volumes_resolution_audit"), "` — every candidate: USED / superseded / skipped"),
  paste0("- `", sel_csv("volumes_flagged_not_used"), "` — machine-readable version of the table above"),
  paste0("- `", sel_csv("volumes_taxon_excluded"), "` — species removed by the taxon filter, with why"),
  paste0("- `", sel_csv("volumes_source_species_ids"), "` — species-name resolution for sign-off"),
  paste0("- `", sel_csv("volumes_species_sources"), "` — which sources contributed each species"),
  paste0("- `", readme_out, "` — this file"), "",
  "## Changing the selection", "",
  "1. Edit the `select_datasets` tribble in `volumes_compiled_select.R` (item / team / year).",
  "2. If a table is new to the merge, give it a term map:",
  "   `standardized_term_by_reference/<Item>_standardized_terms.csv` (picked up automatically).",
  paste0("3. Add any value vetoes to `", flags_file, "`."),
  "4. Re-run. Nothing else needs editing — this README is regenerated.", "")
writeLines(L, readme_out, useBytes = TRUE)

message("[select] ", nrow(volumes_wide), " species x ", ncol(volumes_wide) - 1, " variables from ",
        nrow(select_datasets), " tables | taxa: ",
        if (identical(taxa_keep, "all")) "all"
          else paste0(paste(taxa_keep, collapse = "/"), " (", nrow(taxon_excluded), " excluded)"),
        " | flagged-not-used: ", sum(skipped$more_recent),
        " (of ", nrow(skipped), " skipped) | review: ", nrow(reviewed),
        " | ties: ", nrow(ties), " | outputs: volumes_*", output_suffix, ".csv + ", readme_out)
