#!/usr/bin/env Rscript
#
# Curate the SELECT volume candidates using DeCasien & Higham (2019) principles.
# Run: Rscript volumes_compiled_select_DeCasien.R
#
# Source basis: DeCasien & Higham, Nature Ecology & Evolution 3 (2019),
# 1483-1493, Methods ("Data collection and compilation") and Supplementary
# Information, Appendix ("Source Notes" and "Measurement Notes").
# DOI: https://doi.org/10.1038/s41559-019-0969-0
#
# The paper weights retained, comparable study estimates by REGION-SPECIFIC
# specimen N, removes repeat measurements of the same individual and region,
# and documents substitutions and anatomical exclusions. It does NOT prescribe
# "newest paper wins" for every overlap. The explicit review file and refusal
# to pool unresolved overlaps below are local, provenance-first safeguards,
# not a claim that the authors used this exact software or review vocabulary.
#
# Input: volumes_resolution_audit_select.csv, generated by
# volumes_compiled_select.R. Unlike volumes_long_select.csv, it includes the
# candidates that lost the original recency selection. Its n_obs is a count of
# rows in a source table, NOT the region-specific specimen N. The selected
# pipeline may already have collapsed individual rows within a source. If a
# published mean includes both shared and new specimens, the curator must
# recalculate the independent portion and document it in value_for_pooling.
#
# On first run this script writes volumes_select_DeCasien_curation.csv as a
# review template, then stops. Fill one row per source/species/variable:
#   decision          include / exclude / hold (default: hold)
#   N_region          positive, non-overlapping specimen N for this region
#   sample_id         stable sample/cohort identifier; reused cohorts share ID
#   specimen_ids      known IDs separated by | (optional, checked for overlap)
#   definition_code   same code ONLY for anatomically comparable measurements
#   independence_basis evidence of distinct specimens if >1 source is included
#   value_for_pooling  optional corrected/independent-subset mean, in mm3
#   reason, evidence  explanation and source for decisions and corrections
# For a partial overlap, keep the mixed-source row on hold or exclude it until
# the independent subset's mean and N have been reconstructed from raw records.
# Do not treat publication, year, team label, or n_obs as proof of independence.
#
# Once every candidate is resolved, the script writes ONLY new, suffixed
# outputs: volumes_resolution_audit_select_DeCasien.csv,
# volumes_cell_status_select_DeCasien.csv, volumes_long_select_DeCasien.csv,
# and volumes_wide_select_DeCasien.csv. It never edits the canonical SELECT
# outputs, the source tables, the review CSV, or restricted files.

script_path <- local({
  a <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  if (length(a)) return(normalizePath(sub("^--file=", "", a[1]), mustWork = TRUE))
  if (requireNamespace("rstudioapi", quietly = TRUE) &&
      rstudioapi::isAvailable()) {
    p <- rstudioapi::getSourceEditorContext()$path
    if (nzchar(p)) return(normalizePath(p, mustWork = TRUE))
  }
  stop("Save the script and run it with Rscript or RStudio Source.", call. = FALSE)
})
folder <- dirname(script_path)
input_file <- file.path(folder, "volumes_resolution_audit_select.csv")
review_file <- file.path(folder, "volumes_select_DeCasien_curation.csv")
out_file <- function(stem) file.path(folder, paste0(stem, "_select_DeCasien.csv"))
read_table <- function(path) {
  read.csv(path, stringsAsFactors = FALSE, check.names = FALSE,
           fileEncoding = "UTF-8-BOM", na.strings = c("", "NA"))
}
write_table <- function(x, path) {
  write.csv(x, path, row.names = FALSE, na = "")
}
txt <- function(x) {
  x <- as.character(x)
  x[is.na(x)] <- ""
  trimws(x)
}
nonempty <- function(x) nzchar(txt(x))
key_of <- function(x) paste(x$Source, x$Species, x$Variable, sep = "\034")

if (!file.exists(input_file)) {
  stop("First run volumes_compiled_select.R to create the SELECT candidate audit.",
       call. = FALSE)
}
candidate <- read_table(input_file)
needed <- c("Source", "Species", "Variable", "Value", "n_obs", "Year",
            "status", "action")
missing <- setdiff(needed, names(candidate))
if (length(missing)) {
  stop("Candidate audit is missing: ", paste(missing, collapse = ", "),
       call. = FALSE)
}
# Compilation is of region volumes, not body/brain mass or other data types.
# Keep one-sided variables distinct from both-hemisphere variables: an
# unsuffixed bilateral value cannot be inferred from a unilateral value here.
candidate <- candidate[grepl("_Vol\\.mm3$", candidate$Variable), , drop = FALSE]
if (!nrow(candidate)) stop("No region-volume candidates found.", call. = FALSE)
candidate$Source <- txt(candidate$Source)
candidate$Species <- txt(candidate$Species)
candidate$Variable <- txt(candidate$Variable)
candidate$action <- tolower(txt(candidate$action))
candidate$Value <- suppressWarnings(as.numeric(candidate$Value))
if (any(!nonempty(candidate$Source) | !nonempty(candidate$Species) |
        !nonempty(candidate$Variable)) ||
    any(!is.finite(candidate$Value) | candidate$Value < 0)) {
  stop("Source, species, variable and non-negative volume are required for ",
       "every candidate.", call. = FALSE)
}
if (any(!candidate$action %in% c("skip", "review", "use"))) {
  stop("Unknown action in the SELECT candidate audit.", call. = FALSE)
}
keys <- key_of(candidate)
if (anyDuplicated(keys)) {
  stop("Candidate keys are not unique by Source, Species and Variable; ",
       "resolve the duplicate rows upstream.", call. = FALSE)
}
if (!"reason" %in% names(candidate)) candidate$reason <- NA_character_
if (!"flag" %in% names(candidate)) candidate$flag <- NA_character_

if (!file.exists(review_file)) {
  skip <- candidate$action == "skip"
  review <- data.frame(
    Source = candidate$Source, Species = candidate$Species,
    Variable = candidate$Variable, Value_original = candidate$Value,
    n_obs_not_N = candidate$n_obs, source_year = candidate$Year,
    base_status = candidate$status, base_action = candidate$action,
    base_flag = candidate$flag, base_reason = candidate$reason,
    decision = ifelse(skip, "exclude", "hold"),
    N_region = NA_real_, sample_id = "", specimen_ids = "",
    definition_code = "", independence_basis = "",
    value_for_pooling = NA_real_,
    reason = ifelse(skip & nonempty(candidate$reason),
                    candidate$reason, ""),
    evidence = ifelse(skip, "volumes_select_value_flags.csv", ""),
    stringsAsFactors = FALSE
  )
  write_table(review, review_file)
  stop("Review template created as volumes_select_DeCasien_curation.csv. ",
       "Complete its decisions and region-specific Ns, then rerun. ",
       "No compiled values have been written.", call. = FALSE)
}

review <- read_table(review_file)
fields <- c("Source", "Species", "Variable", "Value_original", "n_obs_not_N",
            "source_year", "base_action", "decision", "N_region",
            "sample_id", "specimen_ids",
            "definition_code", "independence_basis", "value_for_pooling",
            "reason", "evidence")
missing <- setdiff(fields, names(review))
if (length(missing)) {
  stop("Curation file is missing: ", paste(missing, collapse = ", "),
       call. = FALSE)
}
review$Source <- txt(review$Source)
review$Species <- txt(review$Species)
review$Variable <- txt(review$Variable)
review_key <- key_of(review)
if (anyDuplicated(review_key) ||
    length(review_key) != length(keys) ||
    !setequal(review_key, keys)) {
  stop("Curation keys no longer match the SELECT candidate audit. ",
       "Reconcile added/removed sources before compiling.", call. = FALSE)
}
review <- review[match(keys, review_key), , drop = FALSE]
v0 <- suppressWarnings(as.numeric(review$Value_original))
y0 <- suppressWarnings(as.numeric(review$source_year))
y1 <- suppressWarnings(as.numeric(candidate$Year))
n0 <- suppressWarnings(as.numeric(review$n_obs_not_N))
n1 <- suppressWarnings(as.numeric(candidate$n_obs))
if (any(!is.finite(v0)) ||
    any(abs(v0 - candidate$Value) > 1e-8 * pmax(1, abs(candidate$Value))) ||
    any(is.na(y0) != is.na(y1) |
        (!is.na(y0) & !is.na(y1) & y0 != y1)) ||
    any(is.na(n0) != is.na(n1) |
        (!is.na(n0) & !is.na(n1) & n0 != n1)) ||
    any(tolower(txt(review$base_action)) != candidate$action)) {
  stop("SELECT source values, row counts, years or flag actions changed since ",
       "the curation file was ",
       "made. Review the changed candidates before compiling.", call. = FALSE)
}
decision <- tolower(txt(review$decision))
decision[!nzchar(decision)] <- "hold"
if (any(!decision %in% c("include", "exclude", "hold"))) {
  stop("Curation decision must be include, exclude or hold.", call. = FALSE)
}
if (any(candidate$action == "skip" & decision != "exclude")) {
  stop("A value vetoed by the SELECT flag registry cannot be reinstated here. ",
       "Resolve that flag in the source registry first.", call. = FALSE)
}
n_text <- txt(review$N_region)
region_n <- suppressWarnings(as.numeric(n_text))
if (any(nzchar(n_text) & !is.finite(region_n))) {
  stop("N_region contains non-numeric entries.", call. = FALSE)
}
override_text <- txt(review$value_for_pooling)
override <- suppressWarnings(as.numeric(override_text))
if (any(nzchar(override_text) &
        (!is.finite(override) | override < 0))) {
  stop("value_for_pooling must be a non-negative number in mm3 or blank.",
       call. = FALSE)
}
pool_value <- candidate$Value
pool_value[nzchar(override_text)] <- override[nzchar(override_text)]

candidate$decision <- decision
candidate$N_region <- region_n
candidate$sample_id <- txt(review$sample_id)
candidate$specimen_ids <- txt(review$specimen_ids)
candidate$definition_code <- txt(review$definition_code)
candidate$independence_basis <- txt(review$independence_basis)
candidate$value_for_pooling <- pool_value
candidate$curation_reason <- txt(review$reason)
candidate$curation_evidence <- txt(review$evidence)

# A veto is already documented upstream. All other exclusions must explain
# why, and a changed value must be backed by both a reason and evidence.
bad_exclusion <- decision == "exclude" & candidate$action != "skip" &
  (!nonempty(candidate$curation_reason) |
   !nonempty(candidate$curation_evidence))
changed <- decision == "include" &
  abs(pool_value - candidate$Value) >
    1e-8 * pmax(1, abs(candidate$Value))
bad_override <- changed &
  (!nonempty(candidate$curation_reason) |
   !nonempty(candidate$curation_evidence))
if (any(bad_exclusion | bad_override)) {
  stop("Every new exclusion or changed measurement needs a reason AND ",
       "evidence in the curation file.", call. = FALSE)
}

specimen_tokens <- function(x) {
  if (!nonempty(x)) return(character())
  ids <- tolower(trimws(strsplit(x, "|", fixed = TRUE)[[1]]))
  ids[nzchar(ids)]
}
cell_key <- paste(candidate$Species, candidate$Variable, sep = "\034")
groups <- split(seq_len(nrow(candidate)), cell_key)
resolve_cell <- function(ix) {
  x <- candidate[ix, , drop = FALSE]
  chosen <- x[x$decision == "include", , drop = FALSE]
  issues <- character()
  if (any(x$decision == "hold")) issues <- c(issues, "unresolved candidate")
  if (!nrow(chosen) && !length(issues)) {
    state <- "excluded"
    detail <- "All candidates excluded with a documented reason"
  } else {
    if (!nrow(chosen)) issues <- c(issues, "no retained candidate")
    if (nrow(chosen)) {
      if (any(!is.finite(chosen$N_region) | chosen$N_region < 1 |
              chosen$N_region != floor(chosen$N_region))) {
        issues <- c(issues, "missing/invalid region-specific specimen N")
      }
      if (any(!nonempty(chosen$definition_code))) {
        issues <- c(issues, "anatomical definition not checked")
      } else if (length(unique(chosen$definition_code)) > 1L) {
        issues <- c(issues, "incompatible anatomical definitions")
      }
      if (any(!nonempty(chosen$sample_id))) {
        issues <- c(issues, "sample identity not documented")
      } else if (anyDuplicated(chosen$sample_id)) {
        issues <- c(issues, "same sample counted more than once")
      }
      if (any(!nonempty(chosen$curation_evidence))) {
        issues <- c(issues, "source evidence missing")
      }
      if (any(chosen$action == "review" &
              (!nonempty(chosen$curation_reason) |
               !nonempty(chosen$curation_evidence)))) {
        issues <- c(issues, "review flag not resolved")
      }
      if (nrow(chosen) > 1L &&
          any(!nonempty(chosen$independence_basis))) {
        issues <- c(issues, "independence not demonstrated")
      }
      ids <- lapply(chosen$specimen_ids, specimen_tokens)
      if (any(vapply(ids, anyDuplicated, integer(1)) > 0L) ||
          anyDuplicated(unlist(ids, use.names = FALSE))) {
        issues <- c(issues, "specimen ID repeated")
      }
    }
    state <- if (length(issues)) "needs_review" else "ready"
    detail <- if (length(issues)) paste(unique(issues), collapse = "; ") else ""
  }
  ready <- identical(state, "ready")
  n_total <- if (ready) sum(chosen$N_region) else NA_real_
  value <- if (ready) {
    sum(chosen$N_region * chosen$value_for_pooling) / n_total
  } else NA_real_
  data.frame(
    Species = x$Species[1], Variable = x$Variable[1],
    status = state, issue = detail, n_candidates = nrow(x),
    n_retained = nrow(chosen), Value = value, N_independent = n_total,
    Sources = if (ready) paste(chosen$Source, collapse = "; ") else "",
    sample_ids = if (ready) paste(chosen$sample_id, collapse = "; ") else "",
    definition_code = if (ready) chosen$definition_code[1] else "",
    method = if (!ready) "" else if (nrow(chosen) == 1L) {
      "one retained source"
    } else "region-N-weighted independent sources",
    stringsAsFactors = FALSE
  )
}
cells <- do.call(rbind, lapply(groups, resolve_cell))
rownames(cells) <- NULL
cells <- cells[order(cells$Species, cells$Variable), , drop = FALSE]
cell_status <- cells$status[match(cell_key,
  paste(cells$Species, cells$Variable, sep = "\034"))]
candidate$cell_status <- cell_status
candidate$used_in_final <- candidate$decision == "include" &
  cell_status == "ready"
candidate <- candidate[order(candidate$Species, candidate$Variable,
                              candidate$Source), , drop = FALSE]

write_table(candidate, out_file("volumes_resolution_audit"))
write_table(cells, out_file("volumes_cell_status"))
unresolved <- sum(cells$status == "needs_review")
if (unresolved) {
  old_final <- c(out_file("volumes_long"), out_file("volumes_wide"))
  stop(unresolved, " species-region cell(s) still need review. ",
       "The candidate audit and cell-status report were written; NO final ",
       "long/wide table was produced in this run.",
       if (any(file.exists(old_final)))
         " Previously generated final tables may now be stale." else "",
       " Neither row counts nor a blanket latest-year rule were substituted ",
       "for specimen evidence.", call. = FALSE)
}

long <- cells[cells$status == "ready",
              c("Species", "Variable", "Value", "N_independent", "n_retained",
                "Sources", "sample_ids", "definition_code", "method"),
              drop = FALSE]
if (!nrow(long)) {
  stop("All cells were excluded; no compiled values to write.", call. = FALSE)
}
wide <- reshape(long[c("Species", "Variable", "Value")],
                idvar = "Species", timevar = "Variable", direction = "wide")
names(wide) <- sub("^Value\\.", "", names(wide))
wide <- wide[order(wide$Species), , drop = FALSE]
write_table(long, out_file("volumes_long"))
write_table(wide, out_file("volumes_wide"))
message("Compiled ", nrow(long), " curated species-region values from ",
        sum(candidate$used_in_final), " independently reviewed candidate(s).")
